import { CapexRequest, Vendor, VendorInvite, CapexMasterItem } from './types';
import { finalizeMockCapexMaster } from './greenFieldConstants';
import { brownFieldSeedData } from './brownFieldSeedData';

export const mockVendors: Vendor[] = [
  {
    id: 'v1',
    vendorCode: 'VND-001',
    vendorName: 'Tata Motors Ancillaries',
    category: 'Machinery',
    gstin: '27AABCT3518Q1ZK',
    pan: 'AABCT3518Q',
    contactName: 'Ramesh Tiwari',
    contactEmail: 'ramesh.tiwari@tata-ancillaries.in',
    paymentTerms: 'Net-30',
    bankName: 'HDFC Bank',
    accountNumber: '50200012345678',
    ifsc: 'HDFC0001234',
    onboardedAt: '2023-04-10T09:00:00.000Z',
  },
  {
    id: 'v2',
    vendorCode: 'VND-002',
    vendorName: 'Siemens India',
    category: 'IT',
    gstin: '27AAACS6560P1ZX',
    pan: 'AAACS6560P',
    contactName: 'Anita Sharma',
    contactEmail: 'anita.sharma@siemens.com',
    paymentTerms: 'Net-60',
    bankName: 'Citibank',
    accountNumber: '0123456789',
    ifsc: 'CITI0100000',
    onboardedAt: '2023-06-15T10:30:00.000Z',
  },
  {
    id: 'v3',
    vendorCode: 'VND-003',
    vendorName: 'Bosch Packaging',
    category: 'Tooling',
    gstin: '29AABCB1234A1ZZ',
    pan: 'AABCB1234A',
    contactName: 'Klaus Mueller',
    contactEmail: 'k.mueller@bosch-packaging.in',
    paymentTerms: 'Advance',
    bankName: 'Deutsche Bank',
    accountNumber: '9876543210',
    ifsc: 'DEUT0784BBY',
    onboardedAt: '2023-08-01T08:00:00.000Z',
  },
  {
    id: 'v4',
    vendorCode: 'VND-004',
    vendorName: 'L&T Infrastructure',
    category: 'Infrastructure',
    gstin: '27AAACL1234B1ZP',
    pan: 'AAACL1234B',
    contactName: 'Suresh Iyer',
    contactEmail: 'suresh.iyer@lnt-infra.com',
    paymentTerms: 'Net-30',
    bankName: 'SBI',
    accountNumber: '3456789012345',
    ifsc: 'SBIN0001234',
    onboardedAt: '2022-11-20T11:00:00.000Z',
  },
  {
    id: 'v5',
    vendorCode: 'VND-005',
    vendorName: 'Delta Electronics',
    category: 'Machinery',
    gstin: '07AABCD5678E1ZQ',
    pan: 'AABCD5678E',
    contactName: 'Priya Venkatesh',
    contactEmail: 'p.venkatesh@delta-electronics.in',
    paymentTerms: 'Net-60',
    bankName: 'ICICI Bank',
    accountNumber: '123456789012',
    ifsc: 'ICIC0001234',
    onboardedAt: '2024-01-05T14:00:00.000Z',
  },
];

export const mockRequests: CapexRequest[] = [
  {
    id: 'REQ-001',
    subject: 'CNC Machining Center Upgrade',
    category: 'Machinery',
    quantity: '2 units',
    budget: 5000000,
    priority: 'high',
    justification:
      'Existing CNC centers are 12 years old and require frequent downtime for maintenance, impacting production throughput by 18%.',
    techSpecs: {
      specifications: '5-axis, 800mm x 600mm table, spindle speed up to 12000 RPM. Requires 3-phase 415V, 45kVA. Reinforced concrete floor pad and coolant drainage system.',
      complianceStandards: 'ISO 9001:2015, CE Marking',
    },
    plant: 'jhajjar_p1',
    assignedTo: 'sourcing_member',
    status: 'negotiation',
    fieldType: 'brown_field',
    auctionConfig: {
      startedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      durationDays: 7,
      endsAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
      threshold: 5000000,
    },
    createdBy: 'Arjun Mehta',
    createdAt: '2024-03-01T08:00:00.000Z',
  },
  {
    id: 'REQ-002',
    subject: 'ERP System Expansion',
    category: 'IT',
    quantity: '1 licence (500 users)',
    budget: 1800000,
    priority: 'medium',
    justification:
      'Current ERP does not cover the new plant modules. Expansion required to integrate production planning, procurement, and HR.',
    techSpecs: {
      specifications: '500 concurrent users, 3TB data storage. On-premise installation with cloud backup and VPN access.',
      complianceStandards: 'ISO 27001, GDPR',
    },
    plant: 'ddn_4',
    assignedTo: 'sourcing_member',
    status: 'sourcing',
    createdBy: 'Arjun Mehta',
    createdAt: '2024-03-10T10:00:00.000Z',
  },
  {
    id: 'REQ-003',
    subject: 'Warehouse Conveyor System',
    category: 'Infrastructure',
    quantity: '1 system (120m belt)',
    budget: 3500000,
    priority: 'high',
    justification:
      'Manual material handling in warehouse causes ergonomic risks and limits throughput to 200 units/hour. Automated conveyor targets 600 units/hour.',
    techSpecs: {
      specifications: '600 units/hour capacity, max load 50kg per carrier. 3-phase 415V, 30kVA, VFD controlled. Structural steel support frames, 120m total belt length.',
      complianceStandards: 'CE Marking, IS 13000',
    },
    plant: 'ddn_5',
    assignedTo: 'sourcing_member',
    status: 'buyer_approved',
    createdBy: 'Arjun Mehta',
    createdAt: '2024-02-15T09:00:00.000Z',
  },
  {
    id: 'REQ-004',
    subject: 'Solar Rooftop Installation',
    category: 'Infrastructure',
    quantity: '3 units',
    budget: 2800000,
    priority: 'medium',
    justification:
      'Pune plant energy costs have risen 22% YoY. Rooftop solar installation will offset 40% of grid consumption and reduce carbon footprint as per sustainability targets.',
    techSpecs: {
      specifications: '500 kWp capacity across 3 rooftop sections, monocrystalline panels, grid-tied inverters, SCADA monitoring. Requires structural load assessment and net metering approval.',
      complianceStandards: 'MNRE Guidelines, IS 16169, CEA Regulations 2010',
    },
    plant: 'ddn_6',
    assignedTo: 'sourcing_member',
    status: 'sourcing',
    createdBy: 'Arjun Mehta',
    createdAt: '2024-05-20T09:00:00.000Z',
  },
  {
    id: 'REQ-005',
    subject: 'Precision Lathe Machines',
    category: 'Machinery',
    quantity: '5 units',
    budget: 1200000,
    priority: 'high',
    justification:
      'Ahmedabad plant machining line requires 5 precision lathes to replace ageing equipment causing 12% scrap rate. New machines will bring scrap below 2% and increase line throughput.',
    techSpecs: {
      specifications: 'Swing over bed 380mm, between centres 1000mm, spindle speed 50–3000 RPM, tailstock MT4, digital readout. 3-phase 415V, 7.5kW motor per unit.',
      complianceStandards: 'ISO 1708, BIS IS 1878',
    },
    plant: 'ddn_4',
    assignedTo: 'sourcing_member',
    status: 'buyer_approved',
    createdBy: 'Arjun Mehta',
    createdAt: '2024-01-10T08:00:00.000Z',
  },
  {
    id: 'REQ-006',
    subject: 'Network Security Upgrade',
    category: 'IT',
    quantity: '1 system',
    budget: 600000,
    priority: 'critical',
    justification:
      'Recent audit identified gaps in Jhajjar plant OT network segmentation. Immediate firewall and SIEM deployment required to meet ISO 27001 recertification deadline in Q3 2024.',
    techSpecs: {
      specifications: 'Next-gen firewall (10 Gbps throughput), SIEM with 90-day log retention, IDS/IPS, endpoint protection for 120 nodes. On-premise deployment with cloud management portal.',
      complianceStandards: 'ISO 27001:2022, NIST CSF, IEC 62443',
    },
    plant: 'jhajjar_p1',
    assignedTo: 'sourcing_member',
    status: 'negotiation',
    createdBy: 'Arjun Mehta',
    createdAt: '2024-06-05T10:00:00.000Z',
  },
  {
    id: 'REQ-007',
    subject: 'Forklift Fleet Replacement',
    category: 'Machinery',
    quantity: '8 units',
    budget: 4200000,
    priority: 'high',
    justification:
      'Chennai plant fleet of 8 diesel forklifts are over 10 years old with increasing maintenance costs. Replacement with electric counterbalance forklifts will reduce fuel and maintenance costs by 35%.',
    techSpecs: {
      specifications: '3-tonne capacity electric counterbalance forklift, 48V/600Ah Li-ion battery, 8-hour shift endurance, mast height 5.5m, fork length 1.2m. Includes fast-charger units.',
      complianceStandards: 'IS 7217, CE Marking, OSHA 1910.178',
    },
    plant: 'jhajjar_p1',
    assignedTo: 'sourcing_member',
    status: 'pending_head_approval',
    createdBy: 'Arjun Mehta',
    createdAt: '2024-07-12T09:00:00.000Z',
  },
  {
    id: 'REQ-008',
    subject: 'Automated Welding Robots',
    category: 'Machinery',
    quantity: '3 units',
    budget: 7500000,
    priority: 'high',
    justification:
      'Jhajjar P2 sheet metal line currently uses manual MIG welding, causing inconsistent weld quality and high rework rates. Robotic welding will improve first-pass yield to >98%.',
    techSpecs: {
      specifications: '6-axis robotic welding cell, 1400mm reach, MIG/MAG capable, integrated vision system for seam tracking. 3-phase 415V, 25kVA. Safety fencing and light curtains included.',
      complianceStandards: 'ISO 10218, CE Marking, IS 15614',
    },
    plant: 'jhajjar_p2',
    assignedTo: 'sourcing_member',
    status: 'sourcing',
    createdBy: 'Ravi Kumar',
    createdAt: '2024-08-01T08:00:00.000Z',
  },
  {
    id: 'REQ-009',
    subject: 'Air Compressor Replacement',
    category: 'Infrastructure',
    quantity: '2 units',
    budget: 1100000,
    priority: 'medium',
    justification:
      'Existing reciprocating compressors at Jhajjar P2 are beyond service life. Replacement with oil-free screw compressors will cut energy consumption by 30% and eliminate maintenance downtime.',
    techSpecs: {
      specifications: 'Oil-free rotary screw compressor, 75kW, 10 bar, 13.5 m³/min FAD. Variable speed drive, integrated dryer and filter package. ISO Class 0 air quality.',
      complianceStandards: 'ISO 8573-1 Class 0, PED 2014/68/EU, BIS IS 5456',
    },
    plant: 'jhajjar_p2',
    assignedTo: 'sourcing_member',
    status: 'submitted',
    createdBy: 'Ravi Kumar',
    createdAt: '2024-09-10T09:00:00.000Z',
  },
  {
    id: 'REQ-010',
    subject: 'Greenfield Plant — Assembly Line Phase 1',
    category: 'Machinery',
    quantity: '1 line',
    budget: 120000000,
    priority: 'critical',
    justification:
      'New greenfield plant build requires Phase 1 assembly line machinery as part of the overall site development programme.',
    techSpecs: {
      specifications: 'Fully automated assembly line, 120 units/hour capacity, integrated quality stations.',
      complianceStandards: 'ISO 9001:2015, CE Marking',
    },
    plant: 'jhajjar_p1',
    fieldType: 'green_field',
    masterItemId: 'cm-gf-p1-005',
    assignedTo: 'sourcing_member',
    status: 'pending_head_approval',
    createdBy: 'Arjun Mehta',
    createdAt: '2024-10-01T08:00:00.000Z',
    lineItems: [
      {
        id: 'li-gf-001',
        masterItemId: 'cm-gf-p1-005',
        masterHead: 'Assembly',
        division: 'Machinery',
        machineCapacity: '120 units/hour',
        description: 'Assembly line — Phase 1',
        category: 'Machinery',
        quantity: '1',
        budget: 120000000,
        remarks: 'Primary production line for new greenfield plant.',
      },
    ],
  },
];

export const mockInvites: VendorInvite[] = [
  {
    id: 'inv-001',
    requestId: 'REQ-001',
    vendorId: 'v1',
    token: 'tok_VND001_REQ001',
    status: 'negotiating',
    auctionApprovalStatus: 'approved',
    quotes: [
      {
        id: 'q-001-1',
        price: 4800000,
        deliveryDays: 90,
        validUntil: '2024-06-30T00:00:00.000Z',
        attachmentName: 'tata_quote_v1.pdf',
        note: 'Includes installation and 1-year AMC.',
        submittedAt: '2024-03-15T10:00:00.000Z',
      },
      {
        id: 'q-001-2',
        price: 4600000,
        deliveryDays: 85,
        validUntil: '2024-07-15T00:00:00.000Z',
        attachmentName: 'tata_quote_v2.pdf',
        note: 'Revised price after scope discussion. AMC extended to 2 years.',
        submittedAt: '2024-03-28T14:00:00.000Z',
      },
    ],
    negotiationThread: [
      {
        id: 'nm-001-1',
        by: 'sourcing',
        senderName: 'Neha Kapoor',
        message: 'Your initial quote exceeds our budget. Can you revise to below ₹46L with 2-year AMC?',
        counterPrice: 4600000,
        at: '2024-03-20T09:30:00.000Z',
      },
      {
        id: 'nm-001-2',
        by: 'supplier',
        senderName: 'Ramesh Tiwari',
        message: 'We can offer ₹46L with 2-year AMC as requested, but delivery moves to 85 days.',
        counterPrice: 4600000,
        at: '2024-03-22T11:00:00.000Z',
      },
      {
        id: 'nm-001-3',
        by: 'sourcing',
        senderName: 'Neha Kapoor',
        message: '85 days is acceptable. Please submit revised quote formally.',
        at: '2024-03-24T10:00:00.000Z',
      },
    ],
    invitedAt: '2024-03-12T08:00:00.000Z',
  },
  {
    id: 'inv-002',
    requestId: 'REQ-001',
    vendorId: 'v2',
    token: 'tok_VND002_REQ001',
    status: 'negotiating',
    auctionApprovalStatus: 'approved',
    quotes: [
      {
        id: 'q-002-1',
        price: 5100000,
        deliveryDays: 75,
        validUntil: '2024-06-30T00:00:00.000Z',
        attachmentName: 'siemens_quote_cnc.pdf',
        note: 'Premium build quality, faster delivery.',
        submittedAt: '2024-03-16T12:00:00.000Z',
      },
    ],
    negotiationThread: [
      {
        id: 'nm-002-1',
        by: 'sourcing',
        senderName: 'Neha Kapoor',
        message: 'Price is above budget. Can you match ₹48L with 1-year AMC included?',
        counterPrice: 4800000,
        at: '2024-03-21T10:00:00.000Z',
      },
    ],
    invitedAt: '2024-03-12T08:00:00.000Z',
  },
  {
    id: 'inv-003',
    requestId: 'REQ-001',
    vendorId: 'v3',
    token: 'tok_VND003_REQ001',
    status: 'quote_received',
    auctionApprovalStatus: 'approved',
    quotes: [
      {
        id: 'q-003-1',
        price: 4900000,
        deliveryDays: 100,
        validUntil: '2024-07-01T00:00:00.000Z',
        attachmentName: 'bosch_cnc_quote.pdf',
        note: 'European-spec machine, longer delivery due to import.',
        submittedAt: '2024-03-18T09:00:00.000Z',
      },
    ],
    negotiationThread: [],
    invitedAt: '2024-03-12T08:00:00.000Z',
  },
  {
    id: 'inv-004',
    requestId: 'REQ-001',
    vendorId: 'v4',
    token: 'tok_VND004_REQ001',
    status: 'invited',
    auctionApprovalStatus: 'not_sent',
    quotes: [],
    negotiationThread: [],
    invitedAt: '2024-03-13T08:00:00.000Z',
  },
  {
    id: 'inv-005',
    requestId: 'REQ-002',
    vendorId: 'v5',
    token: 'tok_VND005_REQ002',
    status: 'invited',
    auctionApprovalStatus: 'not_sent',
    quotes: [],
    negotiationThread: [],
    invitedAt: '2024-03-18T10:00:00.000Z',
  },
  {
    id: 'inv-006',
    requestId: 'REQ-003',
    vendorId: 'v1',
    token: 'tok_VND001_REQ003',
    status: 'approved',
    auctionApprovalStatus: 'approved',
    quotes: [
      {
        id: 'q-006-1',
        price: 3200000,
        deliveryDays: 60,
        validUntil: '2024-05-31T00:00:00.000Z',
        attachmentName: 'tata_conveyor_quote.pdf',
        note: 'Turnkey installation included.',
        submittedAt: '2024-03-01T11:00:00.000Z',
      },
    ],
    negotiationThread: [],
    invitedAt: '2024-02-25T09:00:00.000Z',
  },
];

const greenFieldMockCapexMaster: CapexMasterItem[] = [
  // Green Field demo — sectioned structure (FY 2025-26, RAC)
  { id: 'cm-gf-p1-001', fieldType: 'green_field', projectType: 'rac', fy: '2025-26', plant: 'jhajjar_p1', division: 'Plant Machinery', head: 'Press Shop', department: 'Production', subParticulars: '6 Axis Robot — press shop line 1', rate: 0.21, totalCost: 1.26 },
  { id: 'cm-gf-p1-002', fieldType: 'green_field', projectType: 'rac', fy: '2025-26', plant: 'jhajjar_p1', division: 'Plant Machinery', head: 'Assembly Shop', department: 'Sheet Metal', subParticulars: 'Power Press (200T)', rate: 0.35, totalCost: 1.40 },
  { id: 'cm-gf-p1-003', fieldType: 'green_field', projectType: 'rac', fy: '2025-26', plant: 'jhajjar_p1', division: 'Compliances', head: 'Compliances', department: 'Civil', subParticulars: 'Admin block civil works', rate: 0.50, totalCost: 0.50 },
  { id: 'cm-gf-p1-004', fieldType: 'green_field', projectType: 'rac', fy: '2025-26', plant: 'jhajjar_p1', division: 'Utilities', head: 'Electrical', department: 'Electrical', subParticulars: 'HT substation & transformer', rate: 0.80, totalCost: 0.80 },
  { id: 'cm-gf-p1-005', fieldType: 'green_field', projectType: 'rac', fy: '2025-26', plant: 'jhajjar_p1', division: 'Utilities', head: 'Misc.', department: 'Projects', subParticulars: 'Contingency allocation', rate: 0.25, totalCost: 0.25 },
  { id: 'cm-gf-p2-001', fieldType: 'green_field', projectType: 'rac', fy: '2025-26', plant: 'jhajjar_p2', division: 'Plant Machinery', head: 'Assembly Shop', department: 'Assembly', subParticulars: 'Assembly line — phase 1', rate: 1.20, totalCost: 1.20 },
  { id: 'cm-gf-p2-002', fieldType: 'green_field', projectType: 'rac', fy: '2025-26', plant: 'jhajjar_p2', division: 'Compliances', head: 'Compliances', department: 'Civil', subParticulars: 'Roads & drainage', rate: 0.40, totalCost: 0.40 },
  { id: 'cm-gf-pune-001', fieldType: 'green_field', projectType: 'rac', fy: '2025-26', plant: 'pune', division: 'Plant Machinery', head: 'Research and Development', department: 'Production', subParticulars: 'Vision inspection system', rate: 0.15, totalCost: 0.15 },
  { id: 'cm-gf-pune-002', fieldType: 'green_field', projectType: 'rac', fy: '2025-26', plant: 'pune', division: 'Plant Machinery', head: 'Paint Shop', department: 'Paint Shop', subParticulars: 'Powder coating line', rate: 0.60, totalCost: 0.60 },
  { id: 'cm-gf-pune-003', fieldType: 'green_field', projectType: 'rac', fy: '2025-26', plant: 'pune', division: 'Utilities', head: 'Fire & Safety', department: 'EHS', subParticulars: 'Fire hydrant & sprinkler system', rate: 0.30, totalCost: 0.30 },
  { id: 'cm-gf-pune-004', fieldType: 'green_field', projectType: 'rac', fy: '2025-26', plant: 'pune', division: 'Information Technology', head: 'Information Technology', department: 'IT', subParticulars: 'Core network & server room', rate: 0.20, totalCost: 0.20 },
];

const rawMockCapexMaster: CapexMasterItem[] = [
  ...brownFieldSeedData,
  ...greenFieldMockCapexMaster,
];

export const mockCapexMaster = finalizeMockCapexMaster(rawMockCapexMaster);
