import { CapexRequest, Vendor, VendorInvite, CapexMasterItem } from './types';

export const mockVendors: Vendor[] = [
  {
    id: 'v1',
    vendorCode: 'VND-001',
    vendorName: 'Tata Motors Ancillaries',
    category: 'Machinery',
    gstin: '27AABCT3518Q1ZK',
    pan: 'AABCT3518Q',
    contactName: 'Ramesh Tiwari',
    contactEmail: 'ramesh.tiwari@tata-ancillaries.in',
    paymentTerms: 'Net-30',
    bankName: 'HDFC Bank',
    accountNumber: '50200012345678',
    ifsc: 'HDFC0001234',
    onboardedAt: '2023-04-10T09:00:00.000Z',
  },
  {
    id: 'v2',
    vendorCode: 'VND-002',
    vendorName: 'Siemens India',
    category: 'IT',
    gstin: '27AAACS6560P1ZX',
    pan: 'AAACS6560P',
    contactName: 'Anita Sharma',
    contactEmail: 'anita.sharma@siemens.com',
    paymentTerms: 'Net-60',
    bankName: 'Citibank',
    accountNumber: '0123456789',
    ifsc: 'CITI0100000',
    onboardedAt: '2023-06-15T10:30:00.000Z',
  },
  {
    id: 'v3',
    vendorCode: 'VND-003',
    vendorName: 'Bosch Packaging',
    category: 'Tooling',
    gstin: '29AABCB1234A1ZZ',
    pan: 'AABCB1234A',
    contactName: 'Klaus Mueller',
    contactEmail: 'k.mueller@bosch-packaging.in',
    paymentTerms: 'Advance',
    bankName: 'Deutsche Bank',
    accountNumber: '9876543210',
    ifsc: 'DEUT0784BBY',
    onboardedAt: '2023-08-01T08:00:00.000Z',
  },
  {
    id: 'v4',
    vendorCode: 'VND-004',
    vendorName: 'L&T Infrastructure',
    category: 'Infrastructure',
    gstin: '27AAACL1234B1ZP',
    pan: 'AAACL1234B',
    contactName: 'Suresh Iyer',
    contactEmail: 'suresh.iyer@lnt-infra.com',
    paymentTerms: 'Net-30',
    bankName: 'SBI',
    accountNumber: '3456789012345',
    ifsc: 'SBIN0001234',
    onboardedAt: '2022-11-20T11:00:00.000Z',
  },
  {
    id: 'v5',
    vendorCode: 'VND-005',
    vendorName: 'Delta Electronics',
    category: 'Machinery',
    gstin: '07AABCD5678E1ZQ',
    pan: 'AABCD5678E',
    contactName: 'Priya Venkatesh',
    contactEmail: 'p.venkatesh@delta-electronics.in',
    paymentTerms: 'Net-60',
    bankName: 'ICICI Bank',
    accountNumber: '123456789012',
    ifsc: 'ICIC0001234',
    onboardedAt: '2024-01-05T14:00:00.000Z',
  },
];

export const mockRequests: CapexRequest[] = [
  {
    id: 'REQ-001',
    subject: 'CNC Machining Center Upgrade',
    category: 'Machinery',
    quantity: '2 units',
    budget: 5000000,
    priority: 'high',
    justification:
      'Existing CNC centers are 12 years old and require frequent downtime for maintenance, impacting production throughput by 18%.',
    techSpecs: {
      specifications: '5-axis, 800mm x 600mm table, spindle speed up to 12000 RPM. Requires 3-phase 415V, 45kVA. Reinforced concrete floor pad and coolant drainage system.',
      complianceStandards: 'ISO 9001:2015, CE Marking',
    },
    plant: 'jhajjar_p1',
    assignedTo: 'sourcing_member',
    status: 'negotiation',
    createdBy: 'Arjun Mehta',
    createdAt: '2024-03-01T08:00:00.000Z',
  },
  {
    id: 'REQ-002',
    subject: 'ERP System Expansion',
    category: 'IT',
    quantity: '1 licence (500 users)',
    budget: 1800000,
    priority: 'medium',
    justification:
      'Current ERP does not cover the new plant modules. Expansion required to integrate production planning, procurement, and HR.',
    techSpecs: {
      specifications: '500 concurrent users, 3TB data storage. On-premise installation with cloud backup and VPN access.',
      complianceStandards: 'ISO 27001, GDPR',
    },
    plant: 'ddn_4',
    assignedTo: 'sourcing_member',
    status: 'sourcing',
    createdBy: 'Arjun Mehta',
    createdAt: '2024-03-10T10:00:00.000Z',
  },
  {
    id: 'REQ-003',
    subject: 'Warehouse Conveyor System',
    category: 'Infrastructure',
    quantity: '1 system (120m belt)',
    budget: 3500000,
    priority: 'high',
    justification:
      'Manual material handling in warehouse causes ergonomic risks and limits throughput to 200 units/hour. Automated conveyor targets 600 units/hour.',
    techSpecs: {
      specifications: '600 units/hour capacity, max load 50kg per carrier. 3-phase 415V, 30kVA, VFD controlled. Structural steel support frames, 120m total belt length.',
      complianceStandards: 'CE Marking, IS 13000',
    },
    plant: 'ddn_5',
    assignedTo: 'sourcing_member',
    status: 'buyer_approved',
    createdBy: 'Arjun Mehta',
    createdAt: '2024-02-15T09:00:00.000Z',
  },
  {
    id: 'REQ-004',
    subject: 'Solar Rooftop Installation',
    category: 'Infrastructure',
    quantity: '3 units',
    budget: 2800000,
    priority: 'medium',
    justification:
      'Pune plant energy costs have risen 22% YoY. Rooftop solar installation will offset 40% of grid consumption and reduce carbon footprint as per sustainability targets.',
    techSpecs: {
      specifications: '500 kWp capacity across 3 rooftop sections, monocrystalline panels, grid-tied inverters, SCADA monitoring. Requires structural load assessment and net metering approval.',
      complianceStandards: 'MNRE Guidelines, IS 16169, CEA Regulations 2010',
    },
    plant: 'ddn_6',
    assignedTo: 'sourcing_member',
    status: 'sourcing',
    createdBy: 'Arjun Mehta',
    createdAt: '2024-05-20T09:00:00.000Z',
  },
  {
    id: 'REQ-005',
    subject: 'Precision Lathe Machines',
    category: 'Machinery',
    quantity: '5 units',
    budget: 1200000,
    priority: 'high',
    justification:
      'Ahmedabad plant machining line requires 5 precision lathes to replace ageing equipment causing 12% scrap rate. New machines will bring scrap below 2% and increase line throughput.',
    techSpecs: {
      specifications: 'Swing over bed 380mm, between centres 1000mm, spindle speed 50–3000 RPM, tailstock MT4, digital readout. 3-phase 415V, 7.5kW motor per unit.',
      complianceStandards: 'ISO 1708, BIS IS 1878',
    },
    plant: 'ddn_4',
    assignedTo: 'sourcing_member',
    status: 'buyer_approved',
    createdBy: 'Arjun Mehta',
    createdAt: '2024-01-10T08:00:00.000Z',
  },
  {
    id: 'REQ-006',
    subject: 'Network Security Upgrade',
    category: 'IT',
    quantity: '1 system',
    budget: 600000,
    priority: 'critical',
    justification:
      'Recent audit identified gaps in Jhajjar plant OT network segmentation. Immediate firewall and SIEM deployment required to meet ISO 27001 recertification deadline in Q3 2024.',
    techSpecs: {
      specifications: 'Next-gen firewall (10 Gbps throughput), SIEM with 90-day log retention, IDS/IPS, endpoint protection for 120 nodes. On-premise deployment with cloud management portal.',
      complianceStandards: 'ISO 27001:2022, NIST CSF, IEC 62443',
    },
    plant: 'jhajjar_p1',
    assignedTo: 'sourcing_member',
    status: 'negotiation',
    createdBy: 'Arjun Mehta',
    createdAt: '2024-06-05T10:00:00.000Z',
  },
  {
    id: 'REQ-007',
    subject: 'Forklift Fleet Replacement',
    category: 'Machinery',
    quantity: '8 units',
    budget: 4200000,
    priority: 'high',
    justification:
      'Chennai plant fleet of 8 diesel forklifts are over 10 years old with increasing maintenance costs. Replacement with electric counterbalance forklifts will reduce fuel and maintenance costs by 35%.',
    techSpecs: {
      specifications: '3-tonne capacity electric counterbalance forklift, 48V/600Ah Li-ion battery, 8-hour shift endurance, mast height 5.5m, fork length 1.2m. Includes fast-charger units.',
      complianceStandards: 'IS 7217, CE Marking, OSHA 1910.178',
    },
    plant: 'jhajjar_p1',
    assignedTo: 'sourcing_member',
    status: 'pending_head_approval',
    createdBy: 'Arjun Mehta',
    createdAt: '2024-07-12T09:00:00.000Z',
  },
  {
    id: 'REQ-008',
    subject: 'Automated Welding Robots',
    category: 'Machinery',
    quantity: '3 units',
    budget: 7500000,
    priority: 'high',
    justification:
      'Jhajjar P2 sheet metal line currently uses manual MIG welding, causing inconsistent weld quality and high rework rates. Robotic welding will improve first-pass yield to >98%.',
    techSpecs: {
      specifications: '6-axis robotic welding cell, 1400mm reach, MIG/MAG capable, integrated vision system for seam tracking. 3-phase 415V, 25kVA. Safety fencing and light curtains included.',
      complianceStandards: 'ISO 10218, CE Marking, IS 15614',
    },
    plant: 'jhajjar_p2',
    assignedTo: 'sourcing_member',
    status: 'sourcing',
    createdBy: 'Ravi Kumar',
    createdAt: '2024-08-01T08:00:00.000Z',
  },
  {
    id: 'REQ-009',
    subject: 'Air Compressor Replacement',
    category: 'Infrastructure',
    quantity: '2 units',
    budget: 1100000,
    priority: 'medium',
    justification:
      'Existing reciprocating compressors at Jhajjar P2 are beyond service life. Replacement with oil-free screw compressors will cut energy consumption by 30% and eliminate maintenance downtime.',
    techSpecs: {
      specifications: 'Oil-free rotary screw compressor, 75kW, 10 bar, 13.5 m³/min FAD. Variable speed drive, integrated dryer and filter package. ISO Class 0 air quality.',
      complianceStandards: 'ISO 8573-1 Class 0, PED 2014/68/EU, BIS IS 5456',
    },
    plant: 'jhajjar_p2',
    assignedTo: 'sourcing_member',
    status: 'submitted',
    createdBy: 'Ravi Kumar',
    createdAt: '2024-09-10T09:00:00.000Z',
  },
];

export const mockInvites: VendorInvite[] = [
  {
    id: 'inv-001',
    requestId: 'REQ-001',
    vendorId: 'v1',
    token: 'tok_VND001_REQ001',
    status: 'negotiating',
    quotes: [
      {
        id: 'q-001-1',
        price: 4800000,
        deliveryDays: 90,
        validUntil: '2024-06-30T00:00:00.000Z',
        attachmentName: 'tata_quote_v1.pdf',
        note: 'Includes installation and 1-year AMC.',
        submittedAt: '2024-03-15T10:00:00.000Z',
      },
      {
        id: 'q-001-2',
        price: 4600000,
        deliveryDays: 85,
        validUntil: '2024-07-15T00:00:00.000Z',
        attachmentName: 'tata_quote_v2.pdf',
        note: 'Revised price after scope discussion. AMC extended to 2 years.',
        submittedAt: '2024-03-28T14:00:00.000Z',
      },
    ],
    negotiationThread: [
      {
        id: 'nm-001-1',
        by: 'sourcing',
        senderName: 'Neha Kapoor',
        message: 'Your initial quote exceeds our budget. Can you revise to below ₹46L with 2-year AMC?',
        counterPrice: 4600000,
        at: '2024-03-20T09:30:00.000Z',
      },
      {
        id: 'nm-001-2',
        by: 'supplier',
        senderName: 'Ramesh Tiwari',
        message: 'We can offer ₹46L with 2-year AMC as requested, but delivery moves to 85 days.',
        counterPrice: 4600000,
        at: '2024-03-22T11:00:00.000Z',
      },
      {
        id: 'nm-001-3',
        by: 'sourcing',
        senderName: 'Neha Kapoor',
        message: '85 days is acceptable. Please submit revised quote formally.',
        at: '2024-03-24T10:00:00.000Z',
      },
    ],
    invitedAt: '2024-03-12T08:00:00.000Z',
  },
  {
    id: 'inv-002',
    requestId: 'REQ-001',
    vendorId: 'v2',
    token: 'tok_VND002_REQ001',
    status: 'negotiating',
    quotes: [
      {
        id: 'q-002-1',
        price: 5100000,
        deliveryDays: 75,
        validUntil: '2024-06-30T00:00:00.000Z',
        attachmentName: 'siemens_quote_cnc.pdf',
        note: 'Premium build quality, faster delivery.',
        submittedAt: '2024-03-16T12:00:00.000Z',
      },
    ],
    negotiationThread: [
      {
        id: 'nm-002-1',
        by: 'sourcing',
        senderName: 'Neha Kapoor',
        message: 'Price is above budget. Can you match ₹48L with 1-year AMC included?',
        counterPrice: 4800000,
        at: '2024-03-21T10:00:00.000Z',
      },
    ],
    invitedAt: '2024-03-12T08:00:00.000Z',
  },
  {
    id: 'inv-003',
    requestId: 'REQ-001',
    vendorId: 'v3',
    token: 'tok_VND003_REQ001',
    status: 'quote_received',
    quotes: [
      {
        id: 'q-003-1',
        price: 4900000,
        deliveryDays: 100,
        validUntil: '2024-07-01T00:00:00.000Z',
        attachmentName: 'bosch_cnc_quote.pdf',
        note: 'European-spec machine, longer delivery due to import.',
        submittedAt: '2024-03-18T09:00:00.000Z',
      },
    ],
    negotiationThread: [],
    invitedAt: '2024-03-12T08:00:00.000Z',
  },
  {
    id: 'inv-004',
    requestId: 'REQ-001',
    vendorId: 'v4',
    token: 'tok_VND004_REQ001',
    status: 'invited',
    quotes: [],
    negotiationThread: [],
    invitedAt: '2024-03-13T08:00:00.000Z',
  },
  {
    id: 'inv-005',
    requestId: 'REQ-002',
    vendorId: 'v5',
    token: 'tok_VND005_REQ002',
    status: 'invited',
    quotes: [],
    negotiationThread: [],
    invitedAt: '2024-03-18T10:00:00.000Z',
  },
  {
    id: 'inv-006',
    requestId: 'REQ-003',
    vendorId: 'v1',
    token: 'tok_VND001_REQ003',
    status: 'approved',
    quotes: [
      {
        id: 'q-006-1',
        price: 3200000,
        deliveryDays: 60,
        validUntil: '2024-05-31T00:00:00.000Z',
        attachmentName: 'tata_conveyor_quote.pdf',
        note: 'Turnkey installation included.',
        submittedAt: '2024-03-01T11:00:00.000Z',
      },
    ],
    negotiationThread: [],
    invitedAt: '2024-02-25T09:00:00.000Z',
  },
];

export const mockCapexMaster: CapexMasterItem[] = [
  // ── Jhajjar Plant 1 ─────────────────────────────────────────────────────────
  // Automation
  { id: 'cm-p1-001', fy: '2025-26', plant: 'jhajjar_p1', head: 'Automation',   department: 'HEX',                       subParticulars: 'HEX Black Copper Detection',                                                                 rate: 0.11,  totalCost: 0.33  },
  { id: 'cm-p1-002', fy: '2025-26', plant: 'jhajjar_p1', head: 'Automation',   department: 'IMM',                       subParticulars: 'Part Conveying system (Injection Machine to Mezzanine) (10 Machines)',                       rate: 1.05,  totalCost: 1.05  },
  { id: 'cm-p1-003', fy: '2025-26', plant: 'jhajjar_p1', head: 'Automation',   department: 'RAC Quality',               subParticulars: 'Printing Part Inspection',                                                                   rate: 0.10,  totalCost: 0.10  },
  { id: 'cm-p1-004', fy: '2025-26', plant: 'jhajjar_p1', head: 'Automation',   department: 'RAC Quality',               subParticulars: 'Remote Testing',                                                                             rate: 0.04,  totalCost: 0.04  },
  { id: 'cm-p1-005', fy: '2025-26', plant: 'jhajjar_p1', head: 'Automation',   department: 'RAC Quality',               subParticulars: 'CFF Testing SPM',                                                                           rate: 0.07,  totalCost: 0.07  },
  { id: 'cm-p1-006', fy: '2025-26', plant: 'jhajjar_p1', head: 'Automation',   department: 'RAC Quality',               subParticulars: 'PCB Checking Jig',                                                                          rate: 0.06,  totalCost: 0.06  },
  // Machinery
  { id: 'cm-p1-007', fy: '2025-26', plant: 'jhajjar_p1', head: 'Machinery',    department: 'HEX',                       subParticulars: 'Shrink less Vertical M/C',                                                                   rate: 2.10,  totalCost: 2.10  },
  { id: 'cm-p1-008', fy: '2025-26', plant: 'jhajjar_p1', head: 'Machinery',    department: 'HEX',                       subParticulars: 'Scissor Lifter',                                                                             rate: 0.05,  totalCost: 0.05  },
  { id: 'cm-p1-009', fy: '2025-26', plant: 'jhajjar_p1', head: 'Machinery',    department: 'HEX',                       subParticulars: 'BOPT (Battery Operated Pallet Truck)',                                                       rate: 0.05,  totalCost: 0.05  },
  // General
  { id: 'cm-p1-010', fy: '2025-26', plant: 'jhajjar_p1', head: 'General',      department: 'IMM',                       subParticulars: 'Centralised Material Feeding for Molding Machines (24 Machines, 450T to 1300T)',              rate: 1.50,  totalCost: 1.50  },
  { id: 'cm-p1-011', fy: '2025-26', plant: 'jhajjar_p1', head: 'General',      department: 'RAC',                       subParticulars: 'Declined Conveyors from Mezzanine to RAC Drop Points',                                      rate: 0.045, totalCost: 0.405 },
  { id: 'cm-p1-012', fy: '2025-26', plant: 'jhajjar_p1', head: 'General',      department: 'Maintenance',               subParticulars: 'DG1010 KVA',                                                                                 rate: 0.75,  totalCost: 0.75  },
  { id: 'cm-p1-013', fy: '2025-26', plant: 'jhajjar_p1', head: 'General',      department: 'Moulding',                  subParticulars: 'Stapping Motor Bush Mould',                                                                  rate: 0.10,  totalCost: 0.10  },
  // Digitization
  { id: 'cm-p1-014', fy: '2025-26', plant: 'jhajjar_p1', head: 'Digitization', department: 'Innovation / Data Analyst', subParticulars: 'Plant ESG/EMS',                                                                             rate: 0.40,  totalCost: 0.40  },
  { id: 'cm-p1-015', fy: '2025-26', plant: 'jhajjar_p1', head: 'Digitization', department: 'Innovation / Data Analyst', subParticulars: 'Trolley RFID Detection',                                                                    rate: 0.00,  totalCost: 0.00  },
  { id: 'cm-p1-016', fy: '2025-26', plant: 'jhajjar_p1', head: 'Digitization', department: 'Innovation / Data Analyst', subParticulars: 'RAC Parameter Monitoring',                                                                  rate: 0.00,  totalCost: 0.00  },
  { id: 'cm-p1-017', fy: '2025-26', plant: 'jhajjar_p1', head: 'Digitization', department: 'Innovation / Data Analyst', subParticulars: 'Manpower & Preventive Monitoring',                                                          rate: 0.00,  totalCost: 0.00  },
  { id: 'cm-p1-018', fy: '2025-26', plant: 'jhajjar_p1', head: 'Digitization', department: 'Innovation / Data Analyst', subParticulars: 'MES for Water Purifier',                                                                    rate: 0.20,  totalCost: 0.20  },
  { id: 'cm-p1-019', fy: '2025-26', plant: 'jhajjar_p1', head: 'Digitization', department: 'Maintenance',               subParticulars: 'Digital Competency for Utility',                                                            rate: 0.00,  totalCost: 0.19  },
  // New Business
  { id: 'cm-p1-020', fy: '2025-26', plant: 'jhajjar_p1', head: 'New Business', department: 'Hex',                       subParticulars: 'Mezzanine, Goods Lift & Utilities',                                                          rate: 2.10,  totalCost: 2.10  },
  // Misc.
  { id: 'cm-p1-021', fy: '2025-26', plant: 'jhajjar_p1', head: 'Misc.',        department: '',                          subParticulars: '',                                                                                           rate: 0.25,  totalCost: 0.25  },

  // ── Jhajjar Plant 2 ─────────────────────────────────────────────────────────
  // Automation
  { id: 'cm-p2-001', fy: '2025-26', plant: 'jhajjar_p2', head: 'Automation',        department: 'Assembly',   subParticulars: 'PD Gun, Fan Torque Tool, Label Printing & pasting, Carton box pick & Place, Valve plate SPM',              rate: 0.60,  totalCost: 0.60 },
  { id: 'cm-p2-002', fy: '2025-26', plant: 'jhajjar_p2', head: 'Automation',        department: 'Copper',     subParticulars: 'Auto Brazing - Induction (Copper Shop)',                                                                   rate: 0.36,  totalCost: 0.36 },
  { id: 'cm-p2-003', fy: '2025-26', plant: 'jhajjar_p2', head: 'Automation',        department: 'Copper',     subParticulars: 'Auto Brazing - PNG (Copper Shop) i4 Inhouse',                                                              rate: 0.30,  totalCost: 0.30 },
  { id: 'cm-p2-004', fy: '2025-26', plant: 'jhajjar_p2', head: 'Automation',        department: 'Assembly',   subParticulars: 'Compressor lifting SPM',                                                                                   rate: 0.00,  totalCost: 0.00 },
  { id: 'cm-p2-005', fy: '2025-26', plant: 'jhajjar_p2', head: 'Automation',        department: 'Assembly',   subParticulars: 'Auto Shut off gun (Made in Japan or Korea)',                                                               rate: 0.10,  totalCost: 0.10 },
  { id: 'cm-p2-006', fy: '2025-26', plant: 'jhajjar_p2', head: 'Automation',        department: 'Hex',        subParticulars: 'Black copper detection',                                                                                   rate: 0.04,  totalCost: 0.29 },
  { id: 'cm-p2-007', fy: '2025-26', plant: 'jhajjar_p2', head: 'Automation',        department: 'Hex',        subParticulars: 'Lacing Conveyor 5 mm',                                                                                    rate: 0.05,  totalCost: 0.05 },
  { id: 'cm-p2-008', fy: '2025-26', plant: 'jhajjar_p2', head: 'Automation',        department: 'Dispatch',   subParticulars: 'Auto Scanning & Tracking of the loading/unloading',                                                       rate: 0.10,  totalCost: 0.10 },
  // Machinery
  { id: 'cm-p2-009', fy: '2025-26', plant: 'jhajjar_p2', head: 'Machinery',         department: 'IMM',        subParticulars: 'Injection moulding machine for Odu Fan guard to reduction of RMC (Set of 2 Machines)',                    rate: 2.92,  totalCost: 2.92 },
  { id: 'cm-p2-010', fy: '2025-26', plant: 'jhajjar_p2', head: 'Machinery',         department: 'Copper',     subParticulars: 'IDU Setup for I4 - Adding 1200 nos. per day - Copper shop',                                              rate: 1.20,  totalCost: 1.20 },
  { id: 'cm-p2-011', fy: '2025-26', plant: 'jhajjar_p2', head: 'Machinery',         department: 'Press',      subParticulars: 'RTS Replacement (Press Shop Line 1)',                                                                      rate: 0.10,  totalCost: 0.60 },
  { id: 'cm-p2-012', fy: '2025-26', plant: 'jhajjar_p2', head: 'Machinery',         department: 'Tool Room',  subParticulars: 'Universal vertical milling machine',                                                                      rate: 0.17,  totalCost: 0.17 },
  { id: 'cm-p2-013', fy: '2025-26', plant: 'jhajjar_p2', head: 'Machinery',         department: 'Store',      subParticulars: 'Jib Crane',                                                                                               rate: 0.15,  totalCost: 0.15 },
  { id: 'cm-p2-014', fy: '2025-26', plant: 'jhajjar_p2', head: 'Machinery',         department: 'Store',      subParticulars: 'Sami Automatic electric Stucker',                                                                         rate: 0.08,  totalCost: 0.08 },
  { id: 'cm-p2-015', fy: '2025-26', plant: 'jhajjar_p2', head: 'Machinery',         department: 'Quality',    subParticulars: 'Dummy Vacuum setup at Line 2 (75K each dummy @ 42 pumps) - 200 LPM',                                     rate: 0.01,  totalCost: 0.32 },
  { id: 'cm-p2-016', fy: '2025-26', plant: 'jhajjar_p2', head: 'Machinery',         department: 'Utility',    subParticulars: 'DG Sync Panel',                                                                                           rate: 0.50,  totalCost: 0.50 },
  { id: 'cm-p2-017', fy: '2025-26', plant: 'jhajjar_p2', head: 'Machinery',         department: 'Utility',    subParticulars: 'APFC Panel',                                                                                              rate: 0.05,  totalCost: 0.05 },
  { id: 'cm-p2-018', fy: '2025-26', plant: 'jhajjar_p2', head: 'Machinery',         department: 'Utility',    subParticulars: 'Diesel Storage & Distribution Management - Datum',                                                        rate: 0.04,  totalCost: 0.04 },
  // General
  { id: 'cm-p2-019', fy: '2025-26', plant: 'jhajjar_p2', head: 'General',           department: 'Building',   subParticulars: 'Mezzanine on the above of Assembly line 2 (30000 Sq. Feet @ 1300/Sq. Feet)',                             rate: 3.90,  totalCost: 3.90 },
  { id: 'cm-p2-020', fy: '2025-26', plant: 'jhajjar_p2', head: 'General',           department: 'Hex',        subParticulars: 'Fin Press puff cabin',                                                                                    rate: 0.25,  totalCost: 0.25 },
  { id: 'cm-p2-021', fy: '2025-26', plant: 'jhajjar_p2', head: 'General',           department: 'Store',      subParticulars: 'MS rack for RM Storage',                                                                                  rate: 0.03,  totalCost: 0.30 },
  { id: 'cm-p2-022', fy: '2025-26', plant: 'jhajjar_p2', head: 'General',           department: 'Maint',      subParticulars: 'Maint Store cabin & Storage rack',                                                                        rate: 0.11,  totalCost: 0.11 },
  // Digitization
  { id: 'cm-p2-023', fy: '2025-26', plant: 'jhajjar_p2', head: 'Digitization',      department: '',           subParticulars: 'New Machine Integration + Plant ESG/EMS + Manpower Cost Monitoring + Preventive module',                 rate: 0.50,  totalCost: 0.50 },
  { id: 'cm-p2-024', fy: '2025-26', plant: 'jhajjar_p2', head: 'Digitization',      department: '',           subParticulars: 'Digital competency for utility',                                                                          rate: 0.00,  totalCost: 0.19 },
  // Misc.
  { id: 'cm-p2-025', fy: '2025-26', plant: 'jhajjar_p2', head: 'Misc.',             department: '',           subParticulars: 'Sudden Expenses / Unplanned Additions',                                                                   rate: 0.20,  totalCost: 0.20 },

  // ── DDN-4 ────────────────────────────────────────────────────────────────────
  // Automation
  { id: 'cm-d4-001', fy: '2025-26', plant: 'ddn_4', head: 'Automation',   department: '', subParticulars: '6 Axis Robot (with Accessories) on line 1 press shop',              rate: 0.21,   totalCost: 1.26  },
  { id: 'cm-d4-002', fy: '2025-26', plant: 'ddn_4', head: 'Automation',   department: '', subParticulars: 'Vision Camera on Hair pin bender',                                   rate: 0.1175, totalCost: 0.47  },
  // Machinery
  { id: 'cm-d4-003', fy: '2025-26', plant: 'ddn_4', head: 'Machinery',    department: '', subParticulars: 'Press machine',                                                       rate: 0.35,   totalCost: 1.40  },
  { id: 'cm-d4-004', fy: '2025-26', plant: 'ddn_4', head: 'Machinery',    department: '', subParticulars: 'Paint oven (HE)',                                                     rate: 0.20,   totalCost: 0.20  },
  { id: 'cm-d4-005', fy: '2025-26', plant: 'ddn_4', head: 'Machinery',    department: '', subParticulars: 'Vacuum Leak Testing Machine',                                         rate: 0.10,   totalCost: 0.20  },
  { id: 'cm-d4-006', fy: '2025-26', plant: 'ddn_4', head: 'Machinery',    department: '', subParticulars: '450 CFM Compressor',                                                  rate: 0.20,   totalCost: 0.20  },
  { id: 'cm-d4-007', fy: '2025-26', plant: 'ddn_4', head: 'Machinery',    department: '', subParticulars: 'Radial Drill Machine',                                                rate: 0.06,   totalCost: 0.06  },
  { id: 'cm-d4-008', fy: '2025-26', plant: 'ddn_4', head: 'Machinery',    department: '', subParticulars: 'Spot Welding Machine (50 KVA)',                                       rate: 0.045,  totalCost: 0.045 },
  // General
  { id: 'cm-d4-009', fy: '2025-26', plant: 'ddn_4', head: 'General',      department: '', subParticulars: 'Magnetic Resonator',                                                  rate: 0.10,   totalCost: 0.10  },
  { id: 'cm-d4-010', fy: '2025-26', plant: 'ddn_4', head: 'General',      department: '', subParticulars: 'Vertical Expander (Modification)',                                    rate: 0.12,   totalCost: 0.12  },
  { id: 'cm-d4-011', fy: '2025-26', plant: 'ddn_4', head: 'General',      department: '', subParticulars: 'Electrical Wiring & Panel',                                           rate: 0.15,   totalCost: 0.15  },
  { id: 'cm-d4-012', fy: '2025-26', plant: 'ddn_4', head: 'General',      department: '', subParticulars: 'Delta Meter',                                                         rate: 0.03,   totalCost: 0.03  },
  { id: 'cm-d4-013', fy: '2025-26', plant: 'ddn_4', head: 'General',      department: '', subParticulars: 'Thyristor Based APFC Panel for 750 KVA Transformer',                 rate: 0.15,   totalCost: 0.15  },
  { id: 'cm-d4-014', fy: '2025-26', plant: 'ddn_4', head: 'General',      department: '', subParticulars: 'Paint Shop Lab',                                                      rate: 0.07,   totalCost: 0.07  },
  // Digitization
  { id: 'cm-d4-015', fy: '2025-26', plant: 'ddn_4', head: 'Digitization', department: '', subParticulars: 'SCADA System for Spray Paint Shop',                                   rate: 0.50,   totalCost: 0.50  },
  { id: 'cm-d4-016', fy: '2025-26', plant: 'ddn_4', head: 'Digitization', department: '', subParticulars: 'Strengthening Existing System, 3 New Machine Integration & Control Room', rate: 0.20, totalCost: 0.20 },
  // Misc.
  { id: 'cm-d4-017', fy: '2025-26', plant: 'ddn_4', head: 'Misc.',        department: '', subParticulars: 'LPG Area / HE FG Area & Utility Civil Work',                         rate: 0.20,   totalCost: 0.20  },
  { id: 'cm-d4-018', fy: '2025-26', plant: 'ddn_4', head: 'Misc.',        department: '', subParticulars: 'Mopping Machine & Accessories',                                       rate: 0.12,   totalCost: 0.12  },
  // New Business
  { id: 'cm-d4-019', fy: '2025-26', plant: 'ddn_4', head: 'New Business', department: '', subParticulars: 'Eva Cutting (N-Series) Machine',                                      rate: 0.08,   totalCost: 0.08  },

  // ── DDN-5 ────────────────────────────────────────────────────────────────────
  // Automation
  { id: 'cm-d5-001', fy: '2025-26', plant: 'ddn_5', head: 'Automation',               department: 'Production',   subParticulars: 'Auto Sleeve Cutting Machine',                                                                          rate: 0.03,   totalCost: 0.03   },
  { id: 'cm-d5-002', fy: '2025-26', plant: 'ddn_5', head: 'Automation',               department: 'Production',   subParticulars: 'Auto Manual Accessories Making Machine',                                                               rate: 0.15,   totalCost: 0.15   },
  { id: 'cm-d5-003', fy: '2025-26', plant: 'ddn_5', head: 'Automation',               department: 'Production',   subParticulars: 'Condenser Conveyor for Condenser Brazing (Belt to Slat)',                                              rate: 0.05,   totalCost: 0.05   },
  { id: 'cm-d5-004', fy: '2025-26', plant: 'ddn_5', head: 'Automation',               department: 'Production',   subParticulars: 'Auto Capillary Bending Machine',                                                                      rate: 0.02,   totalCost: 0.02   },
  { id: 'cm-d5-005', fy: '2025-26', plant: 'ddn_5', head: 'Automation',               department: 'Copper Shop',  subParticulars: 'Auto Induction Brazing Machine',                                                                      rate: 0.42,   totalCost: 0.42   },
  { id: 'cm-d5-006', fy: '2025-26', plant: 'ddn_5', head: 'Automation',               department: 'Copper Shop',  subParticulars: 'Both End Forming Machine',                                                                            rate: 0.07,   totalCost: 0.22   },
  { id: 'cm-d5-007', fy: '2025-26', plant: 'ddn_5', head: 'Automation',               department: 'Copper Shop',  subParticulars: 'CNC Auto Bending (Connector Bending)',                                                                rate: 0.16,   totalCost: 0.32   },
  { id: 'cm-d5-008', fy: '2025-26', plant: 'ddn_5', head: 'Automation',               department: 'Copper Shop',  subParticulars: 'Drilling Machine Automation',                                                                         rate: 0.026,  totalCost: 0.026  },
  { id: 'cm-d5-009', fy: '2025-26', plant: 'ddn_5', head: 'Automation',               department: 'Maintenance',  subParticulars: 'Auto Palletization in Packing Line WAC',                                                              rate: 0.24,   totalCost: 0.24   },
  { id: 'cm-d5-010', fy: '2025-26', plant: 'ddn_5', head: 'Automation',               department: 'Quality',      subParticulars: 'PCB Final Inspection Setup - Inverter',                                                               rate: 0.15,   totalCost: 0.15   },
  { id: 'cm-d5-011', fy: '2025-26', plant: 'ddn_5', head: 'Automation',               department: 'Quality',      subParticulars: 'PCB Final Inspection Setup - FS',                                                                     rate: 0.05,   totalCost: 0.05   },
  { id: 'cm-d5-012', fy: '2025-26', plant: 'ddn_5', head: 'Automation',               department: 'Quality',      subParticulars: 'Remote Auto Inspection Setup',                                                                        rate: 0.18,   totalCost: 0.18   },
  { id: 'cm-d5-013', fy: '2025-26', plant: 'ddn_5', head: 'Automation',               department: 'Maintenance',  subParticulars: 'Scissor Conveyor for Material Unloading (Bhagat Ji Area)',                                           rate: 0.05,   totalCost: 0.05   },
  { id: 'cm-d5-014', fy: '2025-26', plant: 'ddn_5', head: 'Automation',               department: 'Quality',      subParticulars: 'EVV Valve Checking Jig',                                                                              rate: 0.07,   totalCost: 0.07   },
  // Productivity Improvement
  { id: 'cm-d5-015', fy: '2025-26', plant: 'ddn_5', head: 'Productivity Improvement', department: 'Maintenance',  subParticulars: 'Vacuum Pump Shifter Shaft Replaced with Screw',                                                      rate: 0.06,   totalCost: 0.12   },
  { id: 'cm-d5-016', fy: '2025-26', plant: 'ddn_5', head: 'Productivity Improvement', department: 'Maintenance',  subParticulars: 'Vacuum Pump Busbar Replacement Line 3 - Saba Engg',                                                  rate: 0.004,  totalCost: 0.06   },
  { id: 'cm-d5-017', fy: '2025-26', plant: 'ddn_5', head: 'Productivity Improvement', department: 'Maintenance',  subParticulars: 'Vacuum Pump ED30A for Line Due to Lifespan Over',                                                    rate: 0.012,  totalCost: 0.12   },
  { id: 'cm-d5-018', fy: '2025-26', plant: 'ddn_5', head: 'Productivity Improvement', department: 'Maintenance',  subParticulars: 'HVIR Kikisui for ODU Line',                                                                           rate: 0.065,  totalCost: 0.065  },
  { id: 'cm-d5-019', fy: '2025-26', plant: 'ddn_5', head: 'Productivity Improvement', department: 'Maintenance',  subParticulars: 'AVR for All Lines - Lifespan Over',                                                                   rate: 0.011,  totalCost: 0.044  },
  { id: 'cm-d5-020', fy: '2025-26', plant: 'ddn_5', head: 'Productivity Improvement', department: 'Production',   subParticulars: 'Merge Line 02 or Line 03',                                                                            rate: 0.90,   totalCost: 0.90   },
  // Standardization
  { id: 'cm-d5-021', fy: '2025-26', plant: 'ddn_5', head: 'Standardization',          department: 'Innovation',   subParticulars: 'Centralized Reliability Room for DDN Units with ALC Modification',                                   rate: 0.20,   totalCost: 0.20   },
  { id: 'cm-d5-022', fy: '2025-26', plant: 'ddn_5', head: 'Standardization',          department: 'Maintenance',  subParticulars: 'Mezzanine in Store Area',                                                                             rate: 0.30,   totalCost: 0.30   },
  { id: 'cm-d5-023', fy: '2025-26', plant: 'ddn_5', head: 'Standardization',          department: 'Maintenance',  subParticulars: 'Shutter in Dispatch Gate and Unloading Point',                                                       rate: 0.01,   totalCost: 0.02   },
  // Digitization
  { id: 'cm-d5-024', fy: '2025-26', plant: 'ddn_5', head: 'Digitization',             department: 'Maintenance',  subParticulars: 'Diesel Dispenser in Diesel Tank',                                                                    rate: 0.02,   totalCost: 0.02   },
  { id: 'cm-d5-025', fy: '2025-26', plant: 'ddn_5', head: 'Digitization',             department: 'Maintenance',  subParticulars: 'LPG Meter for Assembly Shop & Copper Shop',                                                          rate: 0.0015, totalCost: 0.00   },
  { id: 'cm-d5-026', fy: '2025-26', plant: 'ddn_5', head: 'Digitization',             department: 'Maintenance',  subParticulars: 'Digital Gas Saver on Line',                                                                          rate: 0.007,  totalCost: 0.04   },
  { id: 'cm-d5-027', fy: '2025-26', plant: 'ddn_5', head: 'Digitization',             department: 'Innovation',   subParticulars: 'Assembly Line Traceability Software',                                                                rate: 0.00,   totalCost: 0.36   },
  { id: 'cm-d5-028', fy: '2025-26', plant: 'ddn_5', head: 'Digitization',             department: 'Innovation',   subParticulars: 'Assembly Line Traceability Hardware',                                                                rate: 0.00,   totalCost: 0.54   },
  // Safety
  { id: 'cm-d5-029', fy: '2025-26', plant: 'ddn_5', head: 'Safety',                  department: 'Copper Shop',  subParticulars: 'Safety Sensors Fool-Proofing Centralized System on Copper Shop Machines & Sensitive Areas',          rate: 0.30,   totalCost: 0.30   },
  { id: 'cm-d5-030', fy: '2025-26', plant: 'ddn_5', head: 'Safety',                  department: 'Maintenance',  subParticulars: 'Flux Tank Replacement Due to Lifespan Over',                                                         rate: 0.005,  totalCost: 0.05   },
  { id: 'cm-d5-031', fy: '2025-26', plant: 'ddn_5', head: 'Safety',                  department: 'Maintenance',  subParticulars: 'Goods Lift CU & Assembly Shop Auto Door System with Beam Sensor',                                   rate: 0.05,   totalCost: 0.05   },
  // Business Requirement
  { id: 'cm-d5-032', fy: '2025-26', plant: 'ddn_5', head: 'Business Requirement',    department: 'Copper Shop',  subParticulars: 'Vibrator Deburring & Shining Machine',                                                               rate: 0.09,   totalCost: 0.09   },
  { id: 'cm-d5-033', fy: '2025-26', plant: 'ddn_5', head: 'Business Requirement',    department: 'Copper Shop',  subParticulars: 'Strainer In-house Manufacturing',                                                                    rate: 0.10,   totalCost: 0.30   },
  { id: 'cm-d5-034', fy: '2025-26', plant: 'ddn_5', head: 'Business Requirement',    department: 'Copper Shop',  subParticulars: 'Bench Drilling Machine',                                                                              rate: 0.025,  totalCost: 0.05   },
  // Quality
  { id: 'cm-d5-035', fy: '2025-26', plant: 'ddn_5', head: 'Quality',                 department: 'Quality',      subParticulars: '2-Dtek',                                                                                              rate: 0.03,   totalCost: 0.03   },
  { id: 'cm-d5-036', fy: '2025-26', plant: 'ddn_5', head: 'Quality',                 department: 'Quality',      subParticulars: 'HLD 6000 Probe (2 Nos)',                                                                              rate: 0.035,  totalCost: 0.07   },
  { id: 'cm-d5-037', fy: '2025-26', plant: 'ddn_5', head: 'Quality',                 department: 'Quality',      subParticulars: 'Quality Instrument',                                                                                  rate: 0.10,   totalCost: 0.10   },
  // General
  { id: 'cm-d5-038', fy: '2025-26', plant: 'ddn_5', head: 'General',                 department: 'HR',           subParticulars: 'New Parking Area',                                                                                    rate: 0.05,   totalCost: 0.05   },
  { id: 'cm-d5-039', fy: '2025-26', plant: 'ddn_5', head: 'General',                 department: 'Maintenance',  subParticulars: 'Roof Extractor for Brazing Area (Copper Shop)',                                                      rate: 0.007,  totalCost: 0.07   },
  { id: 'cm-d5-040', fy: '2025-26', plant: 'ddn_5', head: 'General',                 department: 'Maintenance',  subParticulars: 'Exhaust Fan on Store Area and Assembly Line',                                                        rate: 0.005,  totalCost: 0.01   },

  // ── DDN-6 ────────────────────────────────────────────────────────────────────
  // Automation
  { id: 'cm-d6-001', fy: '2025-26', plant: 'ddn_6', head: 'Automation',   department: '', subParticulars: 'RAC IDU Packaging Strapping Machine Auto Mode and Arch Height Short (600mm)',              rate: 0.08,    totalCost: 0.08  },
  { id: 'cm-d6-002', fy: '2025-26', plant: 'ddn_6', head: 'Automation',   department: '', subParticulars: 'RAC ODU HVIR in Auto Mode Before LQC',                                                     rate: 0.02,    totalCost: 0.02  },
  { id: 'cm-d6-003', fy: '2025-26', plant: 'ddn_6', head: 'Automation',   department: '', subParticulars: 'HEX Camera for Black Copper Hairpin + Conveyor',                                           rate: 0.115,   totalCost: 0.12  },
  { id: 'cm-d6-004', fy: '2025-26', plant: 'ddn_6', head: 'Automation',   department: '', subParticulars: 'Robot for 1700 Ton 6 Axis with Insert Fitting (1-Way Cassette)',                          rate: 0.15,    totalCost: 0.15  },
  { id: 'cm-d6-005', fy: '2025-26', plant: 'ddn_6', head: 'Automation',   department: '', subParticulars: 'New Mold Robot Fixtures',                                                                   rate: 0.05,    totalCost: 0.05  },
  { id: 'cm-d6-006', fy: '2025-26', plant: 'ddn_6', head: 'Automation',   department: '', subParticulars: 'New VFD for O2 Plant Air Compressor',                                                      rate: 0.04,    totalCost: 0.04  },
  { id: 'cm-d6-007', fy: '2025-26', plant: 'ddn_6', head: 'Automation',   department: '', subParticulars: 'Main Electrical Panel Changed with DG Sync & Load Balance',                               rate: 0.50,    totalCost: 0.50  },
  // Machinery
  { id: 'cm-d6-008', fy: '2025-26', plant: 'ddn_6', head: 'Machinery',    department: '', subParticulars: '1.5 & 2.5 Row Tooling for CAC Vertical Expander Machine',                                 rate: 0.13,    totalCost: 0.13  },
  { id: 'cm-d6-009', fy: '2025-26', plant: 'ddn_6', head: 'Machinery',    department: '', subParticulars: 'CAC Coil Leak Testing Machine (VLT)',                                                      rate: 0.50,    totalCost: 0.50  },
  { id: 'cm-d6-010', fy: '2025-26', plant: 'ddn_6', head: 'Machinery',    department: '', subParticulars: 'New Molding Machine 1300 Ton',                                                             rate: 2.00,    totalCost: 2.00  },
  { id: 'cm-d6-011', fy: '2025-26', plant: 'ddn_6', head: 'Machinery',    department: '', subParticulars: 'New Molding Machine 450 Ton & 550 Ton',                                                   rate: 0.90,    totalCost: 1.80  },
  // General
  { id: 'cm-d6-012', fy: '2025-26', plant: 'ddn_6', head: 'General',      department: '', subParticulars: 'LQC Dummy Transfer System',                                                                rate: 0.14,    totalCost: 0.14  },
  { id: 'cm-d6-013', fy: '2025-26', plant: 'ddn_6', head: 'General',      department: '', subParticulars: 'Dummy Panel and Wiring Modification',                                                      rate: 0.0095,  totalCost: 0.24  },
  { id: 'cm-d6-014', fy: '2025-26', plant: 'ddn_6', head: 'General',      department: '', subParticulars: 'LQC Bus Bar Changed (22 Mtr)',                                                             rate: 0.0039,  totalCost: 0.09  },
  { id: 'cm-d6-015', fy: '2025-26', plant: 'ddn_6', head: 'General',      department: '', subParticulars: 'Quality Instruments for Inspection (Reference Checker HLD 6000, Ash Content Tester, Balancing Machine, Burst Strength Tester, Digital Height Gauge, Pin Gauges, Run-Out Testing, Digital Vernier, Weight Machine, Thickness Meter, Dial Gauge)', rate: 0.19, totalCost: 0.19 },
  { id: 'cm-d6-016', fy: '2025-26', plant: 'ddn_6', head: 'General',      department: '', subParticulars: 'Screw Barrel at 850 Ton, 100 Ton, and 190 Ton',                                           rate: 0.23,    totalCost: 0.23  },
  { id: 'cm-d6-017', fy: '2025-26', plant: 'ddn_6', head: 'General',      department: '', subParticulars: '1300 Ton II & 850 III Toggle Bush Replace',                                               rate: 0.35,    totalCost: 0.35  },
  { id: 'cm-d6-018', fy: '2025-26', plant: 'ddn_6', head: 'General',      department: '', subParticulars: 'Molding Machine Cooling Pipes Fitting Underground',                                       rate: 0.05,    totalCost: 0.05  },
  { id: 'cm-d6-019', fy: '2025-26', plant: 'ddn_6', head: 'General',      department: '', subParticulars: 'LAB UPS Battery',                                                                          rate: 0.10,    totalCost: 0.10  },
  { id: 'cm-d6-020', fy: '2025-26', plant: 'ddn_6', head: 'General',      department: '', subParticulars: 'LAB Instruments as per NABL Audit Requirements',                                          rate: 0.01,    totalCost: 0.01  },
  // Digitization
  { id: 'cm-d6-021', fy: '2025-26', plant: 'ddn_6', head: 'Digitization', department: '', subParticulars: 'RFID Tag',                                                                                 rate: 0.0325,  totalCost: 0.03  },
  { id: 'cm-d6-022', fy: '2025-26', plant: 'ddn_6', head: 'Digitization', department: '', subParticulars: 'Molding Shop and HE Shop, OEE & EMS',                                                    rate: 0.00505, totalCost: 0.18  },
  // Misc.
  { id: 'cm-d6-023', fy: '2025-26', plant: 'ddn_6', head: 'Misc.',        department: '', subParticulars: 'Office Renovation',                                                                        rate: 0.20,    totalCost: 0.20  },
  { id: 'cm-d6-024', fy: '2025-26', plant: 'ddn_6', head: 'Misc.',        department: '', subParticulars: 'CAC Gangway Re-construction & Densification',                                             rate: 0.15,    totalCost: 0.15  },
  { id: 'cm-d6-025', fy: '2025-26', plant: 'ddn_6', head: 'Misc.',        department: '', subParticulars: 'Toilet Work',                                                                              rate: 0.10,    totalCost: 0.10  },
  { id: 'cm-d6-026', fy: '2025-26', plant: 'ddn_6', head: 'Misc.',        department: '', subParticulars: 'Company Vehicle (Bolero)',                                                                 rate: 0.15,    totalCost: 0.15  },
  { id: 'cm-d6-027', fy: '2025-26', plant: 'ddn_6', head: 'Misc.',        department: '', subParticulars: 'Vehicle Parking',                                                                          rate: 0.40,    totalCost: 0.40  },
  { id: 'cm-d6-028', fy: '2025-26', plant: 'ddn_6', head: 'Misc.',        department: '', subParticulars: 'Other',                                                                                    rate: 0.35,    totalCost: 0.35  },
  // New Business
  { id: 'cm-d6-029', fy: '2025-26', plant: 'ddn_6', head: 'New Business', department: '', subParticulars: 'Mezzanine (16000 + 4000 + 3700 + 2500 Sq Ft)',                                           rate: 1.572,   totalCost: 1.57  },
  { id: 'cm-d6-030', fy: '2025-26', plant: 'ddn_6', head: 'New Business', department: '', subParticulars: 'Launcher Hydraulic Lift',                                                                 rate: 0.15,    totalCost: 0.30  },
  { id: 'cm-d6-031', fy: '2025-26', plant: 'ddn_6', head: 'New Business', department: '', subParticulars: 'Conveyor Line for CAC Front Assembly / 1-Way Cassette (55 × 1.2 Mtr)',                  rate: 0.165,   totalCost: 0.17  },
  { id: 'cm-d6-032', fy: '2025-26', plant: 'ddn_6', head: 'New Business', department: '', subParticulars: 'Strapping Machine for Front Grill Assembly',                                              rate: 0.08,    totalCost: 0.08  },
  { id: 'cm-d6-033', fy: '2025-26', plant: 'ddn_6', head: 'New Business', department: '', subParticulars: 'Jig Fixture / Trolley / Tool',                                                           rate: 0.15,    totalCost: 0.15  },
  { id: 'cm-d6-034', fy: '2025-26', plant: 'ddn_6', head: 'New Business', department: '', subParticulars: 'MES System for Front Grill Line & QMS Tablets',                                          rate: 0.10,    totalCost: 0.10  },
  { id: 'cm-d6-035', fy: '2025-26', plant: 'ddn_6', head: 'New Business', department: '', subParticulars: 'New Mold (Chassis I2, Tubing Holder, Motor Cover, EVA Strip)',                          rate: 1.40,    totalCost: 1.40  },
  { id: 'cm-d6-036', fy: '2025-26', plant: 'ddn_6', head: 'New Business', department: '', subParticulars: 'W3 Front Grill Set',                                                                      rate: 0.50,    totalCost: 0.50  },
  { id: 'cm-d6-037', fy: '2025-26', plant: 'ddn_6', head: 'New Business', department: '', subParticulars: 'W4 Inlet Grill (Godrej & Panasonic)',                                                    rate: 0.40,    totalCost: 0.40  },
  { id: 'cm-d6-038', fy: '2025-26', plant: 'ddn_6', head: 'New Business', department: '', subParticulars: 'Rack for Storage',                                                                        rate: 0.05,    totalCost: 0.05  },
  { id: 'cm-d6-039', fy: '2025-26', plant: 'ddn_6', head: 'New Business', department: '', subParticulars: 'Vacuum Pump with Booster 1000 LPM',                                                      rate: 0.04,    totalCost: 0.08  },
  { id: 'cm-d6-040', fy: '2025-26', plant: 'ddn_6', head: 'New Business', department: '', subParticulars: 'HLD 6000 (Qty 1)',                                                                        rate: 0.137,   totalCost: 0.14  },
  { id: 'cm-d6-041', fy: '2025-26', plant: 'ddn_6', head: 'New Business', department: '', subParticulars: 'CAC Dummy (11 TR and 17 TR)',                                                             rate: 0.10,    totalCost: 0.10  },

  // ── SUPA ──────────────────────────────────────────────────────────────────
  // Automation
  { id: 'cm-sp-001', fy: '2025-26', plant: 'supa', head: 'Automation',       department: '', subParticulars: 'Coil Cutting',                                                       rate: 0.04,        totalCost: 0.04   },
  { id: 'cm-sp-002', fy: '2025-26', plant: 'supa', head: 'Automation',       department: '', subParticulars: 'Robot for Moulding Machine 488 Ton & 1100 Ton',                     rate: 0.04,        totalCost: 0.08   },
  { id: 'cm-sp-003', fy: '2025-26', plant: 'supa', head: 'Automation',       department: '', subParticulars: 'Jacket',                                                             rate: 0.0291667,   totalCost: 0.18   },
  { id: 'cm-sp-004', fy: '2025-26', plant: 'supa', head: 'Automation',       department: '', subParticulars: 'Low Cost Automation',                                               rate: 0.02,        totalCost: 0.10   },
  { id: 'cm-sp-005', fy: '2025-26', plant: 'supa', head: 'Automation',       department: '', subParticulars: 'VFD for Press Machine',                                             rate: 0.01,        totalCost: 0.16   },
  { id: 'cm-sp-006', fy: '2025-26', plant: 'supa', head: 'Automation',       department: '', subParticulars: 'Wire Cutting & Bending Setup',                                      rate: 0.07,        totalCost: 0.07   },
  { id: 'cm-sp-007', fy: '2025-26', plant: 'supa', head: 'Automation',       department: '', subParticulars: 'RTS (5 Presses)',                                                   rate: 0.25,        totalCost: 1.25   },
  { id: 'cm-sp-008', fy: '2025-26', plant: 'supa', head: 'Automation',       department: '', subParticulars: 'Arms Robots (6 Axis)',                                              rate: 0.15,        totalCost: 0.30   },
  { id: 'cm-sp-009', fy: '2025-26', plant: 'supa', head: 'Automation',       department: '', subParticulars: 'Tool Storage Rack',                                                 rate: 0.0076923,   totalCost: 0.10   },
  { id: 'cm-sp-010', fy: '2025-26', plant: 'supa', head: 'Automation',       department: '', subParticulars: 'Consumable Items PPEs & Spares Data Display',                      rate: 0.03,        totalCost: 0.03   },
  // Digitization
  { id: 'cm-sp-011', fy: '2025-26', plant: 'supa', head: 'Digitization',     department: '', subParticulars: 'Coil Circuit Checking',                                             rate: 0.08,        totalCost: 0.08   },
  { id: 'cm-sp-012', fy: '2025-26', plant: 'supa', head: 'Digitization',     department: '', subParticulars: 'Cart Management System',                                            rate: 0.20,        totalCost: 0.20   },
  { id: 'cm-sp-013', fy: '2025-26', plant: 'supa', head: 'Digitization',     department: '', subParticulars: 'Energy Monitoring System (ESG Dig Including Digital Water Meter)',  rate: 0.20,        totalCost: 0.20   },
  { id: 'cm-sp-014', fy: '2025-26', plant: 'supa', head: 'Digitization',     department: '', subParticulars: 'OEE & EMS for Press Shop and Molding Shop',                        rate: 0.00505,     totalCost: 0.37   },
  { id: 'cm-sp-015', fy: '2025-26', plant: 'supa', head: 'Digitization',     department: '', subParticulars: 'MES - Software',                                                    rate: 0.04,        totalCost: 0.20   },
  // General
  { id: 'cm-sp-016', fy: '2025-26', plant: 'supa', head: 'General',          department: '', subParticulars: 'Fire Suppression System',                                           rate: 0.0117647,   totalCost: 0.20   },
  { id: 'cm-sp-017', fy: '2025-26', plant: 'supa', head: 'General',          department: '', subParticulars: 'Fire Panel System',                                                 rate: 0.05,        totalCost: 0.05   },
  { id: 'cm-sp-018', fy: '2025-26', plant: 'supa', head: 'General',          department: '', subParticulars: 'Digital Hand Lifter',                                               rate: 0.03,        totalCost: 0.03   },
  { id: 'cm-sp-019', fy: '2025-26', plant: 'supa', head: 'General',          department: '', subParticulars: 'HE Spares',                                                         rate: 0.20,        totalCost: 0.20   },
  { id: 'cm-sp-020', fy: '2025-26', plant: 'supa', head: 'General',          department: '', subParticulars: 'Ertiga 4 Wheeler',                                                  rate: 0.13,        totalCost: 0.13   },
  { id: 'cm-sp-021', fy: '2025-26', plant: 'supa', head: 'General',          department: '', subParticulars: 'Trolley',                                                            rate: 0.005,       totalCost: 0.20   },
  { id: 'cm-sp-022', fy: '2025-26', plant: 'supa', head: 'General',          department: '', subParticulars: 'IT Instrument',                                                     rate: 0.05,        totalCost: 0.05   },
  { id: 'cm-sp-023', fy: '2025-26', plant: 'supa', head: 'General',          department: '', subParticulars: 'Scissor Lift',                                                      rate: 0.10,        totalCost: 0.10   },
  { id: 'cm-sp-024', fy: '2025-26', plant: 'supa', head: 'General',          department: '', subParticulars: 'MBR Change in STP',                                                rate: 0.16,        totalCost: 0.32   },
  { id: 'cm-sp-025', fy: '2025-26', plant: 'supa', head: 'General',          department: '', subParticulars: 'Dust Cartridge Filter',                                             rate: 0.07,        totalCost: 0.14   },
  { id: 'cm-sp-026', fy: '2025-26', plant: 'supa', head: 'General',          department: '', subParticulars: 'Instruments',                                                       rate: 0.012,       totalCost: 0.12   },
  { id: 'cm-sp-027', fy: '2025-26', plant: 'supa', head: 'General',          department: '', subParticulars: 'OHC',                                                               rate: 0.05,        totalCost: 0.05   },
  { id: 'cm-sp-028', fy: '2025-26', plant: 'supa', head: 'General',          department: '', subParticulars: 'Racks & Bins',                                                      rate: 0.001,       totalCost: 0.05   },
  // Misc.
  { id: 'cm-sp-029', fy: '2025-26', plant: 'supa', head: 'Misc.',            department: '', subParticulars: 'Building Repair & Maintenance',                                    rate: 0.15,        totalCost: 0.15   },
  { id: 'cm-sp-030', fy: '2025-26', plant: 'supa', head: 'Misc.',            department: '', subParticulars: 'Others',                                                            rate: 0.026,       totalCost: 0.13   },
  // Moulding Merger
  { id: 'cm-sp-031', fy: '2025-26', plant: 'supa', head: 'Moulding Merger',  department: '', subParticulars: 'Moulding Machine Shifting Work',                                   rate: 0.003125,    totalCost: 0.10   },
  { id: 'cm-sp-032', fy: '2025-26', plant: 'supa', head: 'Moulding Merger',  department: '', subParticulars: 'UPVC Pipeline',                                                     rate: 0.003125,    totalCost: 0.10   },
  { id: 'cm-sp-033', fy: '2025-26', plant: 'supa', head: 'Moulding Merger',  department: '', subParticulars: 'Air Pipeline',                                                      rate: 0.001875,    totalCost: 0.06   },
  { id: 'cm-sp-034', fy: '2025-26', plant: 'supa', head: 'Moulding Merger',  department: '', subParticulars: 'Cooling Tower & Chiller Shifting',                                 rate: 0.025,       totalCost: 0.05   },
  { id: 'cm-sp-035', fy: '2025-26', plant: 'supa', head: 'Moulding Merger',  department: '', subParticulars: 'Auto Conveying',                                                    rate: 0.08,        totalCost: 0.08   },
  { id: 'cm-sp-036', fy: '2025-26', plant: 'supa', head: 'Moulding Merger',  department: '', subParticulars: 'Robots',                                                            rate: 0.003125,    totalCost: 0.10   },
  { id: 'cm-sp-037', fy: '2025-26', plant: 'supa', head: 'Moulding Merger',  department: '', subParticulars: 'Fan Balancing, Ultrasonic & Oven',                                 rate: 0.05,        totalCost: 0.10   },
  { id: 'cm-sp-038', fy: '2025-26', plant: 'supa', head: 'Moulding Merger',  department: '', subParticulars: 'Crane',                                                             rate: 0.04,        totalCost: 0.04   },
  { id: 'cm-sp-039', fy: '2025-26', plant: 'supa', head: 'Moulding Merger',  department: '', subParticulars: 'Cabling Work',                                                      rate: 0.0046875,   totalCost: 0.15   },
  { id: 'cm-sp-040', fy: '2025-26', plant: 'supa', head: 'Moulding Merger',  department: '', subParticulars: 'Utility Work',                                                      rate: 0.10,        totalCost: 0.10   },
  { id: 'cm-sp-041', fy: '2025-26', plant: 'supa', head: 'Moulding Merger',  department: '', subParticulars: 'IDU Line Dismantling & Restoration Work',                          rate: 0.13,        totalCost: 0.13   },
  { id: 'cm-sp-042', fy: '2025-26', plant: 'supa', head: 'Moulding Merger',  department: '', subParticulars: 'Mezzanine Shifting Work',                                           rate: 0.06,        totalCost: 0.06   },
  { id: 'cm-sp-043', fy: '2025-26', plant: 'supa', head: 'Moulding Merger',  department: '', subParticulars: 'Lift Installation',                                                 rate: 0.05,        totalCost: 0.10   },
  { id: 'cm-sp-044', fy: '2025-26', plant: 'supa', head: 'Moulding Merger',  department: '', subParticulars: 'Dock Leveler',                                                      rate: 0.10,        totalCost: 0.20   },
  { id: 'cm-sp-045', fy: '2025-26', plant: 'supa', head: 'Moulding Merger',  department: '', subParticulars: 'Logistic Conveyor',                                                 rate: 0.05,        totalCost: 0.05   },
  { id: 'cm-sp-046', fy: '2025-26', plant: 'supa', head: 'Moulding Merger',  department: '', subParticulars: 'Office Reallocation Work',                                          rate: 0.10,        totalCost: 0.10   },

  // ── RUDRAPUR ──────────────────────────────────────────────────────────────
  // Automation
  { id: 'cm-rp-001', fy: '2025-26', plant: 'rudrapur', head: 'Automation',    department: '', subParticulars: 'Auto Cable Tie Tightening Machine',                                rate: 0.06,        totalCost: 0.06   },
  { id: 'cm-rp-002', fy: '2025-26', plant: 'rudrapur', head: 'Automation',    department: '', subParticulars: 'Induction / Auto Brazing Machine',                                rate: 0.16,        totalCost: 0.16   },
  // Machinery
  { id: 'cm-rp-003', fy: '2025-26', plant: 'rudrapur', head: 'Machinery',     department: '', subParticulars: 'Molding Machine 1100T',                                           rate: 1.35,        totalCost: 2.70   },
  { id: 'cm-rp-004', fy: '2025-26', plant: 'rudrapur', head: 'Machinery',     department: '', subParticulars: 'Moulding Machine 120T',                                           rate: 0.18,        totalCost: 0.36   },
  { id: 'cm-rp-005', fy: '2025-26', plant: 'rudrapur', head: 'Machinery',     department: '', subParticulars: 'Hot Foil Machine',                                                rate: 0.13,        totalCost: 0.13   },
  { id: 'cm-rp-006', fy: '2025-26', plant: 'rudrapur', head: 'Machinery',     department: '', subParticulars: '4-Head Spot Welding',                                             rate: 0.30,        totalCost: 0.30   },
  // General
  { id: 'cm-rp-007', fy: '2025-26', plant: 'rudrapur', head: 'General',       department: '', subParticulars: 'Dehumidifier',                                                    rate: 0.10,        totalCost: 0.10   },
  { id: 'cm-rp-008', fy: '2025-26', plant: 'rudrapur', head: 'General',       department: '', subParticulars: 'Magnetic Gripper for Line 01',                                   rate: 0.05,        totalCost: 0.05   },
  { id: 'cm-rp-009', fy: '2025-26', plant: 'rudrapur', head: 'General',       department: '', subParticulars: 'UPS for Moulding 20 KVA',                                        rate: 0.02,        totalCost: 0.02   },
  { id: 'cm-rp-010', fy: '2025-26', plant: 'rudrapur', head: 'General',       department: '', subParticulars: 'Trolley & Racks for All Shops',                                  rate: 0.20,        totalCost: 0.20   },
  { id: 'cm-rp-011', fy: '2025-26', plant: 'rudrapur', head: 'General',       department: '', subParticulars: 'Measuring Instruments & Equipment',                              rate: 0.03,        totalCost: 0.03   },
  { id: 'cm-rp-012', fy: '2025-26', plant: 'rudrapur', head: 'General',       department: '', subParticulars: 'New ISO Certification Charges (ISO 9001 / ISO 14001 / ISO 45001)', rate: 0.04,      totalCost: 0.04   },
  { id: 'cm-rp-013', fy: '2025-26', plant: 'rudrapur', head: 'General',       department: '', subParticulars: 'Tablet Digimatic Instrument Interlink',                          rate: 0.01,        totalCost: 0.01   },
  { id: 'cm-rp-014', fy: '2025-26', plant: 'rudrapur', head: 'General',       department: '', subParticulars: 'Testing Equipment for Granules & Copper Testing',                rate: 0.05,        totalCost: 0.05   },
  { id: 'cm-rp-015', fy: '2025-26', plant: 'rudrapur', head: 'General',       department: '', subParticulars: 'NX License ID',                                                   rate: 0.045,       totalCost: 0.045  },
  // Digitization
  { id: 'cm-rp-016', fy: '2025-26', plant: 'rudrapur', head: 'Digitization',  department: '', subParticulars: 'Digital Vehicle Tracking (GPS → Dashboard) with ERP Documentation', rate: 0.025,   totalCost: 0.025  },
  { id: 'cm-rp-017', fy: '2025-26', plant: 'rudrapur', head: 'Digitization',  department: '', subParticulars: 'OEE Monitoring for 22 Molding Machines',                         rate: 0.00505,     totalCost: 0.11   },
  { id: 'cm-rp-018', fy: '2025-26', plant: 'rudrapur', head: 'Digitization',  department: '', subParticulars: 'IDU Kit Monitoring with Model',                                  rate: 0.04,        totalCost: 0.04   },
  { id: 'cm-rp-019', fy: '2025-26', plant: 'rudrapur', head: 'Digitization',  department: '', subParticulars: 'Online Monitoring of Water Consumption and ETP Treated Water',   rate: 0.03,        totalCost: 0.03   },
  { id: 'cm-rp-020', fy: '2025-26', plant: 'rudrapur', head: 'Digitization',  department: '', subParticulars: 'Energy Consumption Online Monitoring',                           rate: 0.02,        totalCost: 0.02   },
  { id: 'cm-rp-021', fy: '2025-26', plant: 'rudrapur', head: 'Digitization',  department: '', subParticulars: 'Copper ODU and IDU Packing Line Digitization',                   rate: 0.02,        totalCost: 0.02   },
  { id: 'cm-rp-022', fy: '2025-26', plant: 'rudrapur', head: 'Digitization',  department: '', subParticulars: 'Fire Pump Digitalisation',                                       rate: 0.0075,      totalCost: 0.0075 },
  // Compliance
  { id: 'cm-rp-023', fy: '2025-26', plant: 'rudrapur', head: 'Compliance',    department: '', subParticulars: '',                                                                rate: 0.00,        totalCost: 0.00   },
  // Misc.
  { id: 'cm-rp-024', fy: '2025-26', plant: 'rudrapur', head: 'Misc.',         department: '', subParticulars: 'Utility Area Cover',                                              rate: 0.02,        totalCost: 0.02   },
  { id: 'cm-rp-025', fy: '2025-26', plant: 'rudrapur', head: 'Misc.',         department: '', subParticulars: 'Maintenance Rack',                                                rate: 0.02,        totalCost: 0.02   },
  { id: 'cm-rp-026', fy: '2025-26', plant: 'rudrapur', head: 'Misc.',         department: '', subParticulars: 'New Dryer for PR Compressor',                                    rate: 0.005,       totalCost: 0.005  },
  { id: 'cm-rp-027', fy: '2025-26', plant: 'rudrapur', head: 'Misc.',         department: '', subParticulars: 'HRTC (1 No.)',                                                    rate: 0.04,        totalCost: 0.04   },
  { id: 'cm-rp-028', fy: '2025-26', plant: 'rudrapur', head: 'Misc.',         department: '', subParticulars: 'MTC (1 No.)',                                                     rate: 0.03,        totalCost: 0.03   },
  { id: 'cm-rp-029', fy: '2025-26', plant: 'rudrapur', head: 'Misc.',         department: '', subParticulars: 'MIG Welding Machine',                                             rate: 0.006,       totalCost: 0.006  },
  { id: 'cm-rp-030', fy: '2025-26', plant: 'rudrapur', head: 'Misc.',         department: '', subParticulars: 'Innovation Gallery',                                              rate: 0.025,       totalCost: 0.025  },
  { id: 'cm-rp-031', fy: '2025-26', plant: 'rudrapur', head: 'Misc.',         department: '', subParticulars: 'Control Room for All Dashboards',                                rate: 0.02,        totalCost: 0.02   },
  { id: 'cm-rp-032', fy: '2025-26', plant: 'rudrapur', head: 'Misc.',         department: '', subParticulars: 'A-20 Progressive Tool CTL Die Plate',                            rate: 0.01,        totalCost: 0.01   },
  { id: 'cm-rp-033', fy: '2025-26', plant: 'rudrapur', head: 'Misc.',         department: '', subParticulars: 'Top Cover 1/6 Trimming Tool - New Cutting Plate Punch',          rate: 0.02,        totalCost: 0.02   },
  { id: 'cm-rp-034', fy: '2025-26', plant: 'rudrapur', head: 'Misc.',         department: '', subParticulars: 'Hanger (Qty 500)',                                                rate: 0.05,        totalCost: 0.05   },
  { id: 'cm-rp-035', fy: '2025-26', plant: 'rudrapur', head: 'Misc.',         department: '', subParticulars: 'Gearbox and Bearing Spares for Paint Shop Conveyor',             rate: 0.06,        totalCost: 0.06   },
  { id: 'cm-rp-036', fy: '2025-26', plant: 'rudrapur', head: 'Misc.',         department: '', subParticulars: 'Base Locator and Die for Stamping Machine',                      rate: 0.15,        totalCost: 0.15   },
  { id: 'cm-rp-037', fy: '2025-26', plant: 'rudrapur', head: 'Misc.',         department: '', subParticulars: 'Plastic Bin for Storage Racks in Molding Shop',                 rate: 0.01,        totalCost: 0.01   },
  { id: 'cm-rp-038', fy: '2025-26', plant: 'rudrapur', head: 'Misc.',         department: '', subParticulars: 'Hydraulic Power Pack (1 No.)',                                   rate: 0.02,        totalCost: 0.02   },
  { id: 'cm-rp-039', fy: '2025-26', plant: 'rudrapur', head: 'Misc.',         department: '', subParticulars: 'Chain Sling with Latch Hooks (4 Nos.)',                          rate: 0.015,       totalCost: 0.015  },
  { id: 'cm-rp-040', fy: '2025-26', plant: 'rudrapur', head: 'Misc.',         department: '', subParticulars: 'Air Blower Fume Duct & Burner Fume Duct',                        rate: 0.02,        totalCost: 0.02   },
  { id: 'cm-rp-041', fy: '2025-26', plant: 'rudrapur', head: 'Misc.',         department: '', subParticulars: 'Densification of Shop Floor',                                    rate: 0.15,        totalCost: 0.15   },
  // New Business
  { id: 'cm-rp-042', fy: '2025-26', plant: 'rudrapur', head: 'New Business',  department: '', subParticulars: 'Telescopic Conveyor for Granules / PR Material Unloading',       rate: 0.14,        totalCost: 0.14   },
  { id: 'cm-rp-043', fy: '2025-26', plant: 'rudrapur', head: 'New Business',  department: '', subParticulars: 'PR Machine Shifting',                                             rate: 0.35,        totalCost: 0.35   },
  { id: 'cm-rp-044', fy: '2025-26', plant: 'rudrapur', head: 'New Business',  department: '', subParticulars: 'Pipelines and Electrical Work',                                  rate: 0.15,        totalCost: 0.15   },
  { id: 'cm-rp-045', fy: '2025-26', plant: 'rudrapur', head: 'New Business',  department: '', subParticulars: 'Air Compressor (55 KW & 250 CFM)',                               rate: 0.10,        totalCost: 0.10   },
  { id: 'cm-rp-046', fy: '2025-26', plant: 'rudrapur', head: 'New Business',  department: '', subParticulars: 'Stacker and Hand Pallet',                                        rate: 0.04,        totalCost: 0.04   },

  // ── SRI CITY-1 ────────────────────────────────────────────────────────────
  // Automation
  { id: 'cm-sc1-001', fy: '2025-26', plant: 'sircity_1', head: 'Automation',    department: '', subParticulars: 'Robots for Part Removal from Behind the 315T Power Press',     rate: 0.12,        totalCost: 0.60   },
  { id: 'cm-sc1-002', fy: '2025-26', plant: 'sircity_1', head: 'Automation',    department: '', subParticulars: 'Material Conveying System Capacity Increase',                  rate: 0.07,        totalCost: 0.28   },
  { id: 'cm-sc1-003', fy: '2025-26', plant: 'sircity_1', head: 'Automation',    department: '', subParticulars: 'Robot for 450T Moulding Machine',                              rate: 0.075,       totalCost: 0.15   },
  { id: 'cm-sc1-004', fy: '2025-26', plant: 'sircity_1', head: 'Automation',    department: '', subParticulars: 'Vision Camera for Checking Assembled Parts',                   rate: 0.04,        totalCost: 0.04   },
  { id: 'cm-sc1-005', fy: '2025-26', plant: 'sircity_1', head: 'Automation',    department: '', subParticulars: 'Capacitor Scanning in Fixed Speed Mode',                       rate: 0.007,       totalCost: 0.007  },
  // Machinery
  { id: 'cm-sc1-006', fy: '2025-26', plant: 'sircity_1', head: 'Machinery',     department: '', subParticulars: 'Strapping Machine',                                            rate: 0.05,        totalCost: 0.10   },
  { id: 'cm-sc1-007', fy: '2025-26', plant: 'sircity_1', head: 'Machinery',     department: '', subParticulars: 'Grinding Machine',                                             rate: 0.10,        totalCost: 0.10   },
  { id: 'cm-sc1-008', fy: '2025-26', plant: 'sircity_1', head: 'Machinery',     department: '', subParticulars: 'TTR Equipment',                                                rate: 0.045,       totalCost: 0.045  },
  { id: 'cm-sc1-009', fy: '2025-26', plant: 'sircity_1', head: 'Machinery',     department: '', subParticulars: 'Core Coupler Replacement',                                     rate: 0.0001,      totalCost: 0.015  },
  { id: 'cm-sc1-010', fy: '2025-26', plant: 'sircity_1', head: 'Machinery',     department: '', subParticulars: 'Shrink Wrapping Machine',                                      rate: 0.009,       totalCost: 0.009  },
  { id: 'cm-sc1-011', fy: '2025-26', plant: 'sircity_1', head: 'Machinery',     department: '', subParticulars: 'ODU Line 1 & 2 Dummy Modification',                           rate: 0.06,        totalCost: 0.12   },
  { id: 'cm-sc1-012', fy: '2025-26', plant: 'sircity_1', head: 'Machinery',     department: '', subParticulars: 'Collet Charging Coupler / STO 1900FSB R3.8',                  rate: 0.0075,      totalCost: 0.15   },
  { id: 'cm-sc1-013', fy: '2025-26', plant: 'sircity_1', head: 'Machinery',     department: '', subParticulars: 'Punch Former',                                                 rate: 0.01255,     totalCost: 0.01255},
  { id: 'cm-sc1-014', fy: '2025-26', plant: 'sircity_1', head: 'Machinery',     department: '', subParticulars: 'Mold Cleaner Machine',                                         rate: 0.011,       totalCost: 0.011  },
  { id: 'cm-sc1-015', fy: '2025-26', plant: 'sircity_1', head: 'Machinery',     department: '', subParticulars: 'Micro TIG Welding Machine',                                    rate: 0.04,        totalCost: 0.04   },
  { id: 'cm-sc1-016', fy: '2025-26', plant: 'sircity_1', head: 'Machinery',     department: '', subParticulars: 'Manual Forklift 2 Ton',                                        rate: 0.07,        totalCost: 0.07   },
  { id: 'cm-sc1-017', fy: '2025-26', plant: 'sircity_1', head: 'Machinery',     department: '', subParticulars: 'Fabricated Cupboard for Spares',                               rate: 0.005,       totalCost: 0.005  },
  // General
  { id: 'cm-sc1-018', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: '3 Mtr Mezzanine Extension for Mould Storage',                 rate: 0.35,        totalCost: 0.35   },
  { id: 'cm-sc1-019', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'ODU Store Heavy Duty Rack (6 Layers)',                         rate: 0.50,        totalCost: 0.50   },
  { id: 'cm-sc1-020', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'High Reach Truck for Heavy Rack Material Movement',            rate: 0.20,        totalCost: 0.20   },
  { id: 'cm-sc1-021', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Telescopic Conveyor for Truck Loading',                        rate: 0.20,        totalCost: 0.20   },
  { id: 'cm-sc1-022', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Rack for Coil Stacking',                                       rate: 0.22,        totalCost: 0.22   },
  { id: 'cm-sc1-023', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Racking System for RM & FG',                                  rate: 0.01,        totalCost: 0.15   },
  { id: 'cm-sc1-024', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Flame Proof Lights for Mezzanine Area (EPS Storage)',          rate: 0.10,        totalCost: 0.10   },
  { id: 'cm-sc1-025', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Tool Rack Cover with Wooden Ply - Kasna Benchmark',            rate: 0.10,        totalCost: 0.10   },
  { id: 'cm-sc1-026', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Primary + Secondary (Common Hangers)',                         rate: 0.0001,      totalCost: 0.09   },
  { id: 'cm-sc1-027', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Die Handling Stacker',                                         rate: 0.08,        totalCost: 0.08   },
  { id: 'cm-sc1-028', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Stacker for Trolley Double Stacking',                          rate: 0.08,        totalCost: 0.08   },
  { id: 'cm-sc1-029', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Puff Panel for 5 mm Fin Press',                                rate: 0.07,        totalCost: 0.07   },
  { id: 'cm-sc1-030', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Scissor Lift or Inclined Conveyor',                            rate: 0.06,        totalCost: 0.06   },
  { id: 'cm-sc1-031', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Rail System for Mold Transfer',                                rate: 0.03,        totalCost: 0.06   },
  { id: 'cm-sc1-032', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Screen Printing Fixtures',                                     rate: 0.025,       totalCost: 0.05   },
  { id: 'cm-sc1-033', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Hangon Hanger (Spare)',                                        rate: 0.0002,      totalCost: 0.05   },
  { id: 'cm-sc1-034', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Hand Trucks',                                                  rate: 0.0088,      totalCost: 0.0352 },
  { id: 'cm-sc1-035', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Helium Setup - Enclosed Room',                                 rate: 0.015,       totalCost: 0.03   },
  { id: 'cm-sc1-036', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Robot Grippers',                                               rate: 0.03,        totalCost: 0.06   },
  { id: 'cm-sc1-037', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Digital Vernier - 150 mm',                                     rate: 0.01,        totalCost: 0.06   },
  { id: 'cm-sc1-038', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'LCG Gun',                                                      rate: 0.0028,      totalCost: 0.014  },
  { id: 'cm-sc1-039', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Codex Printer',                                                rate: 0.003,       totalCost: 0.003  },
  { id: 'cm-sc1-040', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Coil Preparation Jig ODM',                                     rate: 0.015,       totalCost: 0.015  },
  { id: 'cm-sc1-041', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Spare Battery for Forklift',                                   rate: 0.015,       totalCost: 0.015  },
  { id: 'cm-sc1-042', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Compound Pressure Gauge',                                      rate: 0.0003,      totalCost: 0.015  },
  { id: 'cm-sc1-043', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Auto Shut-Off Gun',                                            rate: 0.00125,     totalCost: 0.0125 },
  { id: 'cm-sc1-044', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Electrical Gun',                                               rate: 0.00145,     totalCost: 0.01015},
  { id: 'cm-sc1-045', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Pneumatic High Pressure Gun',                                  rate: 0.001,       totalCost: 0.01   },
  { id: 'cm-sc1-046', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Digital Torque Meter',                                         rate: 0.01,        totalCost: 0.01   },
  { id: 'cm-sc1-047', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'PCB Inspection Setup',                                         rate: 0.01,        totalCost: 0.01   },
  { id: 'cm-sc1-048', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Racks for Master Samples',                                     rate: 0.01,        totalCost: 0.01   },
  { id: 'cm-sc1-049', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Cooling Fan for Fin Press Stacker',                            rate: 0.002,       totalCost: 0.008  },
  { id: 'cm-sc1-050', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Tooling for Bending Machine',                                  rate: 0.0012,      totalCost: 0.0072 },
  { id: 'cm-sc1-051', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Handheld HLD Probe',                                           rate: 0.0011167,   totalCost: 0.0067 },
  { id: 'cm-sc1-052', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Handheld HLD',                                                 rate: 0.002,       totalCost: 0.006  },
  { id: 'cm-sc1-053', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Impact Wrench (Compressor Fixing Gun)',                        rate: 0.0026,      totalCost: 0.0052 },
  { id: 'cm-sc1-054', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Pallet Lifter Electrical',                                     rate: 0.005,       totalCost: 0.005  },
  { id: 'cm-sc1-055', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'New Models Jigs & Fixture',                                    rate: 0.005,       totalCost: 0.005  },
  { id: 'cm-sc1-056', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Hand Pallet Truck Model HPT 25 N',                             rate: 0.002,       totalCost: 0.004  },
  { id: 'cm-sc1-057', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Hand Pallet Truck',                                            rate: 0.002,       totalCost: 0.006  },
  { id: 'cm-sc1-058', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Flaring Machine Clamping Block',                               rate: 0.0014,      totalCost: 0.0028 },
  { id: 'cm-sc1-059', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Spinning Machine Die/Tool',                                    rate: 0.0024,      totalCost: 0.0024 },
  { id: 'cm-sc1-060', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Cutting Block for Saw Cutting Machine',                        rate: 0.0024,      totalCost: 0.0024 },
  { id: 'cm-sc1-061', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Cutting Block for Saw Cutting Machine',                        rate: 0.0023,      totalCost: 0.0023 },
  { id: 'cm-sc1-062', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Printer - Black & White',                                      rate: 0.0015,      totalCost: 0.0015 },
  { id: 'cm-sc1-063', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'HLD 6000 External Calibrator (R32)',                           rate: 0.05,        totalCost: 0.05   },
  { id: 'cm-sc1-064', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'HLD 3000 External Calibrator',                                 rate: 0.033335,    totalCost: 0.033335},
  { id: 'cm-sc1-065', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Instruments for Inspection',                                   rate: 0.05,        totalCost: 0.05   },
  { id: 'cm-sc1-066', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Fabricated Cupboard for Spares',                               rate: 0.05,        totalCost: 0.05   },
  { id: 'cm-sc1-067', fy: '2025-26', plant: 'sircity_1', head: 'General',       department: '', subParticulars: 'Digital Micrometer',                                           rate: 0.015,       totalCost: 0.015  },
  // Digitization
  { id: 'cm-sc1-068', fy: '2025-26', plant: 'sircity_1', head: 'Digitization',  department: '', subParticulars: 'IMS Documents Digitalization',                                 rate: 0.04,        totalCost: 0.04   },
  { id: 'cm-sc1-069', fy: '2025-26', plant: 'sircity_1', head: 'Digitization',  department: '', subParticulars: 'Android Barcode Scanners',                                     rate: 0.0066,      totalCost: 0.0132 },
  { id: 'cm-sc1-070', fy: '2025-26', plant: 'sircity_1', head: 'Digitization',  department: '', subParticulars: 'OEE Monitoring & EMS for Molding Shop & HE Shop',              rate: 0.00505,     totalCost: 0.23735},
  // Compliance
  { id: 'cm-sc1-071', fy: '2025-26', plant: 'sircity_1', head: 'Compliance',    department: '', subParticulars: 'BIS Testing',                                                   rate: 0.20,        totalCost: 0.20   },
  { id: 'cm-sc1-072', fy: '2025-26', plant: 'sircity_1', head: 'Compliance',    department: '', subParticulars: '3rd Party Testing for RM and Samples',                         rate: 0.003,       totalCost: 0.003  },
  // Misc.
  { id: 'cm-sc1-073', fy: '2025-26', plant: 'sircity_1', head: 'Misc.',         department: '', subParticulars: 'IT Miscellaneous Items + Line Merging',                        rate: 0.05,        totalCost: 2.55   },
  // New Business
  { id: 'cm-sc1-074', fy: '2025-26', plant: 'sircity_1', head: 'New Business',  department: '', subParticulars: 'New Trolleys for MELCO 25/26K Model',                          rate: 0.35,        totalCost: 0.35   },
  { id: 'cm-sc1-075', fy: '2025-26', plant: 'sircity_1', head: 'New Business',  department: '', subParticulars: 'FGL New Business - Packing Development',                       rate: 0.003,       totalCost: 0.45   },
  { id: 'cm-sc1-076', fy: '2025-26', plant: 'sircity_1', head: 'New Business',  department: '', subParticulars: 'MELCO Separate Dock',                                          rate: 0.10,        totalCost: 0.10   },
  { id: 'cm-sc1-077', fy: '2025-26', plant: 'sircity_1', head: 'New Business',  department: '', subParticulars: 'FGL S17/S19 Model Packing Improvement Bins/Box',               rate: 0.0001,      totalCost: 0.09   },

  // ── SRI CITY-2 ────────────────────────────────────────────────────────────
  // Automation
  { id: 'cm-sc2-001', fy: '2025-26', plant: 'sircity_2', head: 'Automation',    department: '', subParticulars: 'Vision Camera for Sticker & Logo Inspection',                  rate: 0.035,       totalCost: 0.14   },
  { id: 'cm-sc2-002', fy: '2025-26', plant: 'sircity_2', head: 'Automation',    department: '', subParticulars: 'Trolley Management System with RFID',                          rate: 0.12,        totalCost: 0.12   },
  { id: 'cm-sc2-003', fy: '2025-26', plant: 'sircity_2', head: 'Automation',    department: '', subParticulars: 'Vision Camera for Part Checking (Channel Plates in Press Shop)', rate: 0.12,      totalCost: 0.12   },
  { id: 'cm-sc2-004', fy: '2025-26', plant: 'sircity_2', head: 'Automation',    department: '', subParticulars: 'Vision Camera (Loading Stage on Either Side)',                 rate: 0.10,        totalCost: 0.10   },
  { id: 'cm-sc2-005', fy: '2025-26', plant: 'sircity_2', head: 'Automation',    department: '', subParticulars: 'Black Tube Sensor for Hair Pin Bender',                        rate: 0.0032,      totalCost: 0.07   },
  { id: 'cm-sc2-006', fy: '2025-26', plant: 'sircity_2', head: 'Automation',    department: '', subParticulars: 'LCA',                                                           rate: 0.50,        totalCost: 0.50   },
  // Machinery
  { id: 'cm-sc2-007', fy: '2025-26', plant: 'sircity_2', head: 'Machinery',     department: '', subParticulars: 'Dry Ice Cleaning System',                                      rate: 0.10,        totalCost: 0.10   },
  { id: 'cm-sc2-008', fy: '2025-26', plant: 'sircity_2', head: 'Machinery',     department: '', subParticulars: 'Capillary Cutting and Beading',                                rate: 0.16,        totalCost: 0.16   },
  { id: 'cm-sc2-009', fy: '2025-26', plant: 'sircity_2', head: 'Machinery',     department: '', subParticulars: 'PCB Inspection Setup',                                         rate: 0.01,        totalCost: 0.01   },
  { id: 'cm-sc2-010', fy: '2025-26', plant: 'sircity_2', head: 'Machinery',     department: '', subParticulars: 'Instruments for Inspection',                                   rate: 0.10,        totalCost: 0.10   },
  { id: 'cm-sc2-011', fy: '2025-26', plant: 'sircity_2', head: 'Machinery',     department: '', subParticulars: 'Spare Battery for Forklift',                                   rate: 0.015,       totalCost: 0.02   },
  { id: 'cm-sc2-012', fy: '2025-26', plant: 'sircity_2', head: 'Machinery',     department: '', subParticulars: 'EOT Crane - Fin Press',                                        rate: 0.15,        totalCost: 0.15   },
  // General
  { id: 'cm-sc2-013', fy: '2025-26', plant: 'sircity_2', head: 'General',       department: '', subParticulars: 'Screen Printing Fixtures',                                     rate: 0.025,       totalCost: 0.05   },
  { id: 'cm-sc2-014', fy: '2025-26', plant: 'sircity_2', head: 'General',       department: '', subParticulars: 'Robot Grippers (Spares)',                                      rate: 0.03,        totalCost: 0.03   },
  { id: 'cm-sc2-015', fy: '2025-26', plant: 'sircity_2', head: 'General',       department: '', subParticulars: 'Hangon Hanger (Spare)',                                        rate: 0.0002,      totalCost: 0.05   },
  { id: 'cm-sc2-016', fy: '2025-26', plant: 'sircity_2', head: 'General',       department: '', subParticulars: 'Digital Torque Meter (Spare)',                                 rate: 0.01,        totalCost: 0.01   },
  { id: 'cm-sc2-017', fy: '2025-26', plant: 'sircity_2', head: 'General',       department: '', subParticulars: 'Cooling Manifold with Hose Pipe & Male/Female Coupler (Spares)', rate: 0.0002,   totalCost: 0.10   },
  { id: 'cm-sc2-018', fy: '2025-26', plant: 'sircity_2', head: 'General',       department: '', subParticulars: 'Collet Charging Coupler / STO 1900FSB R3.8 (Spares)',          rate: 0.0075,      totalCost: 0.15   },
  { id: 'cm-sc2-019', fy: '2025-26', plant: 'sircity_2', head: 'General',       department: '', subParticulars: 'Auto Shutoff Gun',                                             rate: 0.00125,     totalCost: 0.01   },
  { id: 'cm-sc2-020', fy: '2025-26', plant: 'sircity_2', head: 'General',       department: '', subParticulars: 'Pneumatic High Pressure Gun',                                  rate: 0.001,       totalCost: 0.01   },
  { id: 'cm-sc2-021', fy: '2025-26', plant: 'sircity_2', head: 'General',       department: '', subParticulars: 'Electrical Gun',                                               rate: 0.00145,     totalCost: 0.00   },
  { id: 'cm-sc2-022', fy: '2025-26', plant: 'sircity_2', head: 'General',       department: '', subParticulars: 'LCG Gun',                                                      rate: 0.0028,      totalCost: 0.01   },
  { id: 'cm-sc2-023', fy: '2025-26', plant: 'sircity_2', head: 'General',       department: '', subParticulars: 'Impact Wrench (Compressor Fixing Gun)',                        rate: 0.0026,      totalCost: 0.01   },
  { id: 'cm-sc2-024', fy: '2025-26', plant: 'sircity_2', head: 'General',       department: '', subParticulars: '7 mm Manifold Head for VLT',                                  rate: 0.15,        totalCost: 0.30   },
  { id: 'cm-sc2-025', fy: '2025-26', plant: 'sircity_2', head: 'General',       department: '', subParticulars: 'Tooling for Bending Machine',                                  rate: 0.0012,      totalCost: 0.01   },
  { id: 'cm-sc2-026', fy: '2025-26', plant: 'sircity_2', head: 'General',       department: '', subParticulars: 'Spinning Machine Die / Tool',                                  rate: 0.0024,      totalCost: 0.00   },
  { id: 'cm-sc2-027', fy: '2025-26', plant: 'sircity_2', head: 'General',       department: '', subParticulars: 'Flaring Machine Clamping Block',                               rate: 0.0014,      totalCost: 0.00   },
  { id: 'cm-sc2-028', fy: '2025-26', plant: 'sircity_2', head: 'General',       department: '', subParticulars: 'Tool Rack Cover with Wooden Ply - Kasna Benchmark',            rate: 0.10,        totalCost: 0.10   },
  // Digitization
  { id: 'cm-sc2-029', fy: '2025-26', plant: 'sircity_2', head: 'Digitization',  department: '', subParticulars: 'OEE & Energy Monitoring for Press Shop, Molding Shop & HE Shop', rate: 0.00505,  totalCost: 0.51   },
  { id: 'cm-sc2-030', fy: '2025-26', plant: 'sircity_2', head: 'Digitization',  department: '', subParticulars: 'ESG Data Monitoring',                                          rate: 0.003,       totalCost: 0.00   },
  // Compliance
  { id: 'cm-sc2-031', fy: '2025-26', plant: 'sircity_2', head: 'Compliance',    department: '', subParticulars: 'BIS Testing',                                                   rate: 0.20,        totalCost: 0.20   },
  { id: 'cm-sc2-032', fy: '2025-26', plant: 'sircity_2', head: 'Compliance',    department: '', subParticulars: 'HEX License Renewal',                                          rate: 0.05,        totalCost: 0.05   },
  { id: 'cm-sc2-033', fy: '2025-26', plant: 'sircity_2', head: 'Compliance',    department: '', subParticulars: 'Split AC License Renewal',                                     rate: 0.25,        totalCost: 0.25   },
  { id: 'cm-sc2-034', fy: '2025-26', plant: 'sircity_2', head: 'Compliance',    department: '', subParticulars: 'IMS Surveillance Audit',                                       rate: 0.026,       totalCost: 0.03   },
  { id: 'cm-sc2-035', fy: '2025-26', plant: 'sircity_2', head: 'Compliance',    department: '', subParticulars: 'RECD for DG',                                                  rate: 0.30,        totalCost: 0.30   },
  // Misc.
  { id: 'cm-sc2-036', fy: '2025-26', plant: 'sircity_2', head: 'Misc.',         department: '', subParticulars: '3rd Party Test for RM and Samples + Last Year Backlog Capex',  rate: 0.003,       totalCost: 20.00  },
];
